### ISSUE TITLE
ImagePrompt and Inpainting together ?

### ISSUE THREAD

**Issue by bsormagec** [mrhan1993/Fooocus-API#100]
Is there a way to use both of these features at the same time? I know it's available on Fooocus, but I can't seem to find where to input both fields together here. I noticed there's a 'mixing_image_prompt_and_inpaint' option under advanced_params, but I'm not sure how to use it. Thank you for all your great work @konieshadow @mrhan1993

**Comment by konieshadow** [comment]
These APIs are designed to operate independently to meet specific functions. Combination use is not impossible. I will release a new API in a later version to meet the combined use scenario.
Don't close this issue, I will reply when it's done. I've been a little busy lately, sorry.

**Comment by bsormagec** [comment]
I believe that the feature I need already exists on Fooocus. If I can find it on the backend/headless side, I can create it and open a PR. However, I need some clarification when I see 'mixing_image_prompt_and_inpaint' and other features inside the request body.

Thank you. 

> These APIs are designed to operate independently to meet specific functions. Combination use is not impossible. I will release a new API in a later version to meet the combined use scenario. Don't close this issue, I will reply when it's done. I've been a little busy lately, sorry.

**Comment by konieshadow** [comment]
@bsormagec Just add basic support on dev branch. You can try it by calling `Image Prompt` api with new params: intpu_image, input_mask, outpaint_selections, etc.

**Comment by Laidawang** [comment]
@konieshadow Can you provide a simple solution for using image prompt as canny and inpating together？

**Comment by Laidawang** [comment]
> @konieshadow Can you provide a simple solution for using image prompt as canny and inpating together？

solved
