### ISSUE TITLE
focus startup parameters

### ISSUE THREAD

**Issue by Laidawang** [mrhan1993/Fooocus-API#101]
I often use some hyperparameter startup items of fooocus. Can I add it to the api? 
ex：--all-in-fp16 --always-gpu

**Comment by konieshadow** [comment]
@Laidawang Can you test it in `dev` branch? I just add base support for Fooocus cli arguments, and need feedback.

**Comment by Laidawang** [comment]
![image](https://github.com/konieshadow/Fooocus-API/assets/85244566/fc6528ed-310b-42e3-a9a0-c10595e2905a)
i think the --gpu-device-id not work, but --all-in-fp16 works well, Because I didn’t receive cuda out of memory when I used fp16 for the first time, but I did receive it when I used fp32.

**Comment by Laidawang** [comment]
The memory cost seems to be increasing. I consume about 6g of memory in main branch, but using fp16 in the dev branch cost about 12g.

**Comment by konieshadow** [comment]
> ![image](https://private-user-images.githubusercontent.com/85244566/292354900-fc6528ed-310b-42e3-a9a0-c10595e2905a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTQ0MTYsIm5iZiI6MTcwMzIxNDExNiwicGF0aCI6Ii84NTI0NDU2Ni8yOTIzNTQ5MDAtZmM2NTI4ZWQtMzEwYi00MmUzLWE5YTAtYzEwNTk1ZTI5MDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzMDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZjQ0NzgzMTYzNzliYzFlNjU0NzU0ZGZjNjVlODVlYjg5YzFlYzg4NjcyYmNlMmZiYzg0ZmM1MjFhYzFhNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BdHJEDthIgsP1bLz2UtJCD2VxUTe-KvXzzlsC2qk5cs) i think the --gpu-device-id not work, but --all-in-fp16 works well, Because I didn’t receive cuda out of memory when I used fp16 for the first time, but I did receive it when I used fp32.

Missed a block of code for applying '--gpu-device-id'. Just added.

**Comment by konieshadow** [comment]
It's on main branch now.

**Comment by Laidawang** [comment]
cool!!!!
