### ISSUE TITLE
Worker error: not enough values to unpack

### ISSUE THREAD

**Issue by ardha27** [mrhan1993/Fooocus-API#102]
Worker error: not enough values to unpack (expected 2, got 1)
[Task Queue] Finish task with error, seq=1

sorry i duplicate it, because i can't find solution on old issue

**Comment by mrhan1993** [comment]
need more info, command line output, your request data and enpoint

**Comment by konieshadow** [comment]
@ardha27 Could you share your request parameters?

**Comment by ardha27** [comment]
I fix it, so it looks like aspect ratio parameter need unique "x" symbol and if i change it, it return error

**Comment by konieshadow** [comment]
@ardha27 You can use `*`, `x` or `×`.

**Comment by ardha27** [comment]
Thank you

**Comment by bsormagec** [comment]
> I fix it, so it looks like aspect ratio parameter need unique "x" symbol and if i change it, it return error

When I try to use a small x, it crashes. It seems to have a different Unicode.

**Comment by konieshadow** [comment]
@bsormagec Could you try with latest version?
