### ISSUE TITLE
api

### ISSUE THREAD

**Issue by hailowck** [mrhan1993/Fooocus-API#109]
Is api free?

**Comment by hailowck** [comment]
How Do We Fix This?
<img width="720" alt="屏幕截图 2023-12-25 164356" src="https://github.com/konieshadow/Fooocus-API/assets/149397024/707343be-95c3-4df0-bf0b-1fa797a00e95">

**Comment by hailowck** [comment]
> How Do We Fix This?我们如何解决这个问题？ <img alt="屏幕截图 2023-12-25 164356" width="720" src="https://private-user-images.githubusercontent.com/149397024/292736354-707343be-95c3-4df0-bf0b-1fa797a00e95.png?
![Uploading 屏幕截图 2023-12-25 170901.png…]()
jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTU1NzYsIm5iZiI6MTcwMzQ5NTI3NiwicGF0aCI6Ii8xNDkzOTcwMjQvMjkyNzM2MzU0LTcwNzM0M2JlLTk1YzMtNGRmMC1iZjBiLTFmYTc5N2EwMGU5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwOTA3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTYzYjE5MmZlOThhNTNjOTYwZGEwYTgzNDhmOWE1OTJlZTcyNjIwNzQ0YmM2N2Y3MWFmMzlmNWQ3NGE4YjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6qWSUXOsos-r-70vrvet3sF5isYaR7vkIXe6uv3ob2A">

**Comment by hailowck** [comment]
How Do We Fix This?
<img width="857" alt="屏幕截图 2023-12-25 170901" src="https://github.com/konieshadow/Fooocus-API/assets/149397024/d36759c3-9588-4ae1-b2e4-9aa0264eb123">

**Comment by konieshadow** [comment]
@hailowck It looks like your python version not compatible. Python 3.10 or 3.11 is recommend.

**Comment by hailowck** [comment]
@konieshadow I have solved the current problem, but there are new problems.I want to ask something else, is it not necessary to download the model for this project?Can I generate pictures by calling api?Also, does this api need money?Look forward to and thank you for your answer.

**Comment by konieshadow** [comment]
@hailowck The API itself and the code base it relies on are open source, so using them is free. However, image generation often requires the support of valuable hardware resources (especially GPU), so from this perspective, it is not free. For example, if you use a cloud server to deploy code, you need to pay the server rental fee.

**Comment by hailowck** [comment]
@konieshadow thank you,But I don't understand exactly what your project is for now.Do you need foocusontology to use it?

**Comment by mrhan1993** [comment]
@hailowck The project is a Encapsulation of [Fooocus](https://github.com/lllyasviel/Fooocus) and provides some general interface to use [Fooocus](https://github.com/lllyasviel/Fooocus)  programmatically.

**Comment by hailowck** [comment]
@konieshadow ok, thanks
