### ISSUE TITLE
colab timeout?

### ISSUE THREAD

**Issue by mattou78400** [mrhan1993/Fooocus-API#11]
Hi,

I'm trying to run it on colab as such:

```

%cd /content
!git clone https://github.com/konieshadow/Fooocus-API
%cd /content/Fooocus-API
!pip install -r requirements.txt
!pip install pydantic-core
!pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118 xformers

!npm install -g tunnelmole

!curl ipecho.net/plain

!python main.py & tmole 8888

```

But whatever request I make to that endpoint, I'm getting a "504 gateway time-out"
Any idea what that could be or how to fix it?

thanks a lot for that wrapper!

**Comment by konieshadow** [comment]
This is because when run main.py first time, it will download nessary dependencies and load model, which take minutes.
I add a colab.ipynb in this repository, and add colab link in readme.
But I haven't fix the OOM problem.

**Comment by konieshadow** [comment]
Fixed colab OOM by merge the `colab` branch of Fooocus.

**Comment by konieshadow** [comment]
By the way. I see tunnelmole is not stable when proxy long time costing http request, so I change to bore, which is in https://github.com/ekzhang/bore.

**Comment by mattou78400** [comment]
thank you sir!
Works flawlessly :)

**Comment by mattou78400** [comment]
Looks like I'm getting 

`bore_cli::client: connection exited`


Here and there forcing me to re-run the cell to start again

**Comment by konieshadow** [comment]
I'm realy not prefessional about port tunnels. If you want stable connection, you may need commercial services fot that.

Or you can just use replicate to call the api. I made a model on https://replicate.com/konieshadow/fooocus-api.
