### ISSUE TITLE
Request: Allow for custom filenames.

### ISSUE THREAD

**Issue by xvertile** [mrhan1993/Fooocus-API#110]
{
  "prompt": "",
  "negative_prompt": "",
"file_name": "something.png".
  "style_selections": [
    "Fooocus V2",
    "Fooocus Enhance",
    "Fooocus Sharp"
  ],
}
this would be great to have for people that are running this in production to offer to clients.

**Comment by mrhan1993** [comment]
I don't think this is necessary. If you want to provide services to users, you can solve the file name problem through the front end. If you only provide API, then developers can easily customize the file name after receiving the return value.

**Comment by saendu** [comment]
I think it is. If you want to automate something e.g. creating 10k pictures. I would like to directly give them a meaningful name based on the prompt.
