### ISSUE TITLE
API For SVD

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#114]
有兴趣做SVD的api吗
参考项目
https://github.com/xx025/stable-video-diffusion-webui

**Comment by aiwillcoming** [comment]
它也是一个基于gradio的项目，和Fooocus非常类似

**Comment by konieshadow** [comment]
我觉得目前AI视频生成还在快速发展中，还没有一个效果特别好或者特别明朗的统治级模型，所以可能还不到时候吧。另外我个人精力有限，做 Fooocus 的 api 主要起源于个人的需求。
不过鼓励您自己动手试试，会是一个很有意思的过程。

**Comment by mrhan1993** [comment]
@aiwillcoming 个人建议玩玩 [ComfyUI](https://github.com/comfyanonymous/ComfyUI), 别搞什么 webui 了，comfyui巨灵活，而且编程也不是太难

**Comment by aiwillcoming** [comment]
@mrhan1993 过于灵活
