### ISSUE TITLE
Generating up to 3 images at the same time

### ISSUE THREAD

**Issue by trone522** [mrhan1993/Fooocus-API#115]
Hello, 

Is it possible to have a way to generate up to 3 images at the same time from the queue?
If yes the how? 

Thank you

**Comment by konieshadow** [comment]
For the queue size, you can override it by passing `--queue-size` flags, like:
```python mian.py --queue-size 10```

But this will only effect the queue size, you are still generating the images one by one.

**Comment by trone522** [comment]
What would be a work around ?

**Comment by mrhan1993** [comment]
@trone522 Fooocus does not seem to have the concept of batch_size in stable diffusion webui. The image_number in the original project can specify to generate several pictures at a time, but still generate them one by one.
If you have a lot of numeracy, you can try to deploy multiple instances. At present, however, you need to handle the task information between multiple instances yourself.
