### ISSUE TITLE
webhook-url  建议增加每个请求单独设置

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#118]
目前只能启动时设置webhook-url，这样不太灵活
最好是支持每个请求的时候带上webhook-url，如果没有带的话再使用启动参数中的默认webhook-url

**Comment by bsormagec** [comment]
I am planning to do that when i have time. Its in my todo list

**Comment by PlexPt** [comment]
@bsormagec already done
