### ISSUE TITLE
Fooocus-API和GLM3有冲突

### ISSUE THREAD

**Issue by Kimdow220807** [mrhan1993/Fooocus-API#127]
你好，我电脑部署了GLM3和Fooocus-API等开源工具，我发现我用GLM3跑一些长篇一些的对话后，Fooocus-API就变的非常非常慢，关掉GLM3后速度又恢复正常；同样的我用原版的Fooocus是不会又这个问题存在的。

**Comment by aiwillcoming** [comment]
显存不够了，发生了内存交换

**Comment by Kimdow220807** [comment]
> 顯存不夠了，發生了記憶體交換

我用的是4090显卡，主要原版我测试过真的不会出现这个情况

**Comment by konieshadow** [comment]
Fooocus-API 只是 Fooocus 的简单包装，完全复用了原版的工作管线，理论上运行的效果是一致的。
你可以先关闭其他消耗资源的进程，分别单独运行 Fooocus 和 Fooocus-API，检查传入同样参数的情况下生成图片时占用的RAM、CPU、vRAM这些资源的峰值和生成后的回收行为是否一致。
抱歉我这边电脑配置比较拉跨，没办法直接复现您的使用场景。
