### ISSUE TITLE
following the instructions removed my model files!

### ISSUE THREAD

**Issue by Morriz** [mrhan1993/Fooocus-API#130]
Hi, I moved my previously cloned `lllyasviel/Fooocus` to `repositories`, and then ran `python main.py`. This resulted in my model files being deleted and redownloaded ;(

**Comment by mrhan1993** [comment]
I have confirmed how this problem happened. This happens when the Fooocus directory exists and is not a Git repository. We will discuss how to solve this situation more elegantly.

**Comment by mrhan1993** [comment]
@Morriz I changed the logic of Fooocus cloning and detection, and added instructions。thx for your issue
