### ISSUE TITLE
View CDPS and PyraCanny images

### ISSUE THREAD

**Issue by CyrusVorwald** [mrhan1993/Fooocus-API#133]
Is there a way to view the CDPS and PyraCanny images, or use other controlnets?

**Comment by bsormagec** [comment]
They are available right now under inpainting.

**Comment by CyrusVorwald** [comment]
How do I view the output of these controlnet images? This is different from inpainting, I want to see what the CDPS and PyraCanny outputs look like.

**Comment by konieshadow** [comment]
@CyrusVorwald It's not supported by Fooocus now. So you cant do it by the way in ComfyUI or WebUI.

**Comment by CyrusVorwald** [comment]
Got it, closing this
