### ISSUE TITLE
memory occupied slowly increase

### ISSUE THREAD

**Issue by Laidawang** [mrhan1993/Fooocus-API#134]
[https://github.com/lllyasviel/Fooocus/issues/1646](url) The api service I started has been slowly increasing the memory occupied. I'm not sure if this is happening in the fooocus source code or if it's caused by the API.

**Comment by Laidawang** [comment]
python main.py  --host 0.0.0.0  --sync-repo skip --all-in-fp16 --port 8000 --queue-history 1 --always-gpu
Here are my real startup parameters.

**Comment by mashb1t** [comment]
Links to https://github.com/lllyasviel/Fooocus/issues/1646
