### ISSUE TITLE
错误原因未显示出来

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#136]
当出错时，显示
[Task Queue] Finish task with error
但是不知道错误的原因是什么
能否把错误的原因显示出来？

**Comment by aiwillcoming** [comment]
not enough values to unpack (expected 2, got 1)

**Comment by aiwillcoming** [comment]
为AR 参数问题，建议加上校验

**Comment by konieshadow** [comment]
已经加上校验了，感谢贡献者。

**Comment by Laidawang** [comment]
请问是怎么获取错误信息的？ @konieshadow

**Comment by konieshadow** [comment]
> 请问是怎么获取错误信息的？ @konieshadow

此处修复的是具体的某个异常导致的报错没有在控制台中提示原因。
你是想通过接口获取到任务失败的信息吗？

**Comment by aiwillcoming** [comment]
#147

**Comment by Laidawang** [comment]
> > 请问是怎么获取错误信息的？ @konieshadow
> 
> 此处修复的是具体的某个异常导致的报错没有在控制台中提示原因。 你是想通过接口获取到任务失败的信息吗？

对的，比如我的server报错 cuda out of memory 我怎么在调api的时候获取这个信息？
![image](https://github.com/konieshadow/Fooocus-API/assets/85244566/523d42c2-a232-44b8-a054-eb016bd82460)
比如这样，我要在调api的时候拿取这个信息。
