### ISSUE TITLE
FOOOCUS 2.1.857（请求更新）

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#138]

**Comment by mrhan1993** [comment]
@konieshadow was sick, so the response will be slow, please forgive

**Comment by aiwillcoming** [comment]
> @konieshadow was sick, so the response will be slow, please forgive

建议 code review 改为Contributors投票模式,  只要是正式Contributor, 多人投票决定PR是否通过, 渐少创始人精力消耗

**Comment by mrhan1993** [comment]
@aiwillcoming 只要 @konieshadow 愿意，拉个群都行

**Comment by aiwillcoming** [comment]
github 有这个功能

**Comment by mrhan1993** [comment]
> github 有这个功能

嗯，等他决定吧

**Comment by konieshadow** [comment]
> > @konieshadow was sick, so the response will be slow, please forgive
> 
> 建议 code review 改为Contributors投票模式, 只要是正式Contributor, 多人投票决定PR是否通过, 渐少创始人精力消耗

我研究了下，貌似需要引入 [Mergeable](https://github.com/apps/mergeable) App。
我觉得目前还没这个必要，目前贡献者总共也就8位，Watch了项目了也就7个人。
我会尽力保持与Fooocus代码库的同步更新， @mrhan1993 也会去查看并合并 PR 的。望您理解。

**Comment by aiwillcoming** [comment]
当然
