### ISSUE TITLE
image-prompt No Example

### ISSUE THREAD

**Issue by Kimdow220807** [mrhan1993/Fooocus-API#14]
Hello, the other APIs do not have sample code like Text2Img, I do not quite understand how to write the Request body part, can you guide me?

**Comment by konieshadow** [comment]
There are many shared parameters between Text2Img and other apis, but only Text2Img's request body is JSON because it doesn't need file upload. For the shared parameters, just use as Text2Img, except `style_selections` and `loras` are in diffrent formats.

You can just click "Try it out" button on the Swagger-UI, it will show the default request form data.

I will improve the document later. Sorry for now.

And you can check the pameters in Fooocus Gradio Interface, almost same as Fooocus-API.

**Comment by pengpengzi** [comment]
Open the "Inspect" on the page, and then click on "Network". You can see the request package. The request uses form-data format, and you can convert it to JSON. Please note that for image uploads, you should use the file upload method instead of base64 encoding. Below is my request data, hope it helps you.
``` 
data = {
  "sharpness": 2,
  "guidance_scale": 7,
  "cn_type1": "Image Prompt",
  "prompt": "",
  "cn_weight1": "",
  "l1": "sd_xl_offset_example-lora_1.0.safetensors",
  "image_number": "1",
  "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
  "image_seed": -1,
  "style_selections": "Fooocus V2,Default (Slightly Cinematic)",
  "negative_promit": "",
  "w1": 0.5,
  "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
  "cn_stop1": 0.4,
  "aspect_ratios_selection": "1152×896",
  "performance_selection": "Quality"
}

"cn_img1": open(img_path, "rb")
```

**Comment by Kimdow220807** [comment]
> 開啟頁面上的“檢查”，然後按一下“網路”。可以看到請求包。請求使用form-data格式，您可以將其轉換為JSON。請注意，對於圖片上傳，您應該使用檔案上傳方法而不是base64編碼。以下是我的請求數據，希望對您有幫助。
> 
> ```
> data = {
>   "sharpness": 2,
>   "guidance_scale": 7,
>   "cn_type1": "Image Prompt",
>   "prompt": "",
>   "cn_weight1": "",
>   "l1": "sd_xl_offset_example-lora_1.0.safetensors",
>   "image_number": "1",
>   "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
>   "image_seed": -1,
>   "style_selections": "Fooocus V2,Default (Slightly Cinematic)",
>   "negative_promit": "",
>   "w1": 0.5,
>   "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
>   "cn_stop1": 0.4,
>   "aspect_ratios_selection": "1152×896",
>   "performance_selection": "Quality"
> }
> 
> "cn_img1": open(img_path, "rb")
> ```

Thank you, but I'm not sure about the image uploading part, could you be more specific?Doesn't the image need to be written to "data"? How to refer to it?

**Comment by pengpengzi** [comment]
I am not sure which language you are using, but the approach should be the same. I have written the following code in Python and the request was successful. Here is my entire request, hopefully it can provide you with some ideas.
```
img_path = "D:\\00000-0.png"

data = {
    "sharpness": "2",
    "input_mask": "",
    "guidance_scale": "7",
    "prompt": "",
    "l1": "sd_xl_offset_example-lora_1.0.safetensors",
    "image_number": "1",
    "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
    "image_seed": "-1",
    "style_selections": "Fooocus V2,Default (Slightly Cinematic)",
    "negative_promit": "",
    "outpaint_selections": "",
    "w1": "0.5",
    "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
    "aspect_ratios_selection": "1152×896",
    "performance_selection": "Quality",
}

response = requests.post(url, data=data, files={"input_image": open(img_path, "rb")})
```

**Comment by konieshadow** [comment]
Different programming languages and platforms upload files differently. 

Generally speaking, the request body of this interface is multipat/form. Each field is a text or binary stream. The image needs to be placed in the request body as a binary stream or byte array.

**Comment by pengpengzi** [comment]
> > 開啟頁面上的“檢查”，然後按一下“網路”。可以看到請求包。請求使用form-data格式，您可以將其轉換為JSON。請注意，對於圖片上傳，您應該使用檔案上傳方法而不是base64編碼。以下是我的請求數據，希望對您有幫助。
> > ```
> > data = {
> >   "sharpness": 2,
> >   "guidance_scale": 7,
> >   "cn_type1": "Image Prompt",
> >   "prompt": "",
> >   "cn_weight1": "",
> >   "l1": "sd_xl_offset_example-lora_1.0.safetensors",
> >   "image_number": "1",
> >   "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
> >   "image_seed": -1,
> >   "style_selections": "Fooocus V2,Default (Slightly Cinematic)",
> >   "negative_promit": "",
> >   "w1": 0.5,
> >   "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
> >   "cn_stop1": 0.4,
> >   "aspect_ratios_selection": "1152×896",
> >   "performance_selection": "Quality"
> > }
> > 
> > "cn_img1": open(img_path, "rb")
> > ```
> 
> Thank you, but I'm not sure about the image uploading part, could you be more specific?Doesn't the image need to be written to "data"? How to refer to it?

I am not sure which language you are using, but the approach should be the same. I have written the following code in Python and the request was successful. Here is my entire request, hopefully it can provide you with some ideas.
```
img_path = "D:\\00000-0.png"

data = {
    "sharpness": "2",
    "input_mask": "",
    "guidance_scale": "7",
    "prompt": "",
    "l1": "sd_xl_offset_example-lora_1.0.safetensors",
    "image_number": "1",
    "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
    "image_seed": "-1",
    "style_selections": "Fooocus V2,Default (Slightly Cinematic)",
    "negative_promit": "",
    "outpaint_selections": "",
    "w1": "0.5",
    "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
    "aspect_ratios_selection": "1152×896",
    "performance_selection": "Quality",
}

response = requests.post(url, data=data, files={"input_image": open(img_path, "rb")})
```

**Comment by Kimdow220807** [comment]
> I am not sure which language you are using, but the approach should be the same. I have written the following code in Python and the request was successful. Here is my entire request, hopefully it can provide you with some ideas.
> 
> ```
> img_path = "D:\\00000-0.png"
> 
> data = {
>     "sharpness": "2",
>     "input_mask": "",
>     "guidance_scale": "7",
>     "prompt": "",
>     "l1": "sd_xl_offset_example-lora_1.0.safetensors",
>     "image_number": "1",
>     "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
>     "image_seed": "-1",
>     "style_selections": "Fooocus V2,Default (Slightly Cinematic)",
>     "negative_promit": "",
>     "outpaint_selections": "",
>     "w1": "0.5",
>     "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
>     "aspect_ratios_selection": "1152×896",
>     "performance_selection": "Quality",
> }
> 
> response = requests.post(url, data=data, files={"input_image": open(img_path, "rb")})
> ```

I used Python and now I can request successfully but it doesn't work, here is my code:

img_path = 'D:\\test0005.png'
data = {
  "sharpness": 2,
  "guidance_scale": 7,
  "cn_type1": "PyraCanny",
  "prompt": "",
  "cn_weight1": 0.6,
  "l1": "sd_xl_offset_example-lora_1.0.safetensors",
  "image_number": "1",
  "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
  "image_seed": -1,
  "style_selections": "Fooocus V2,SAI Anime",
  "negative_promit": "",
  "w1": 0.5,
  "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
  "cn_stop1": 0.5,
  "aspect_ratios_selection": "1152×896",
  "performance_selection": "Quality",
}

response = requests.post(url = f'{url}/v1/generation/image-prompt', json=data, files={"input_image": open(img_path, "rb")})
image = Image.open(io.BytesIO(base64.b64decode(response.json()[0]["base64"])))
image.save("d://kk.jpg")

**Comment by Kimdow220807** [comment]
response = requests.post(url = f'{url}/v1/generation/image-prompt', json=data, files={"input_image": open(img_path, "rb")})
image = Image.open(io.BytesIO(base64.b64decode(response.json()[0]["base64"])))
image.save("d://kk.jpg")
Can generate images, but it results in an error, "PyraCanny" does not have an effect!

**Comment by Kimdow220807** [comment]
Can generate images, but it results in an error, "PyraCanny" does not have an effect!

**Comment by Kimdow220807** [comment]
> There are many shared parameters between Text2Img and other apis, but only Text2Img's request body is JSON because it doesn't need file upload. For the shared parameters, just use as Text2Img, except `style_selections` and `loras` are in diffrent formats.
> 
> You can just click "Try it out" button on the Swagger-UI, it will show the default request form data.
> 
> I will improve the document later. Sorry for now.
> 
> And you can check the pameters in Fooocus Gradio Interface, almost same as Fooocus-API.

The image-prompt "try it out" button on Swagger-UI to generate base64 and then transfer the image again doesn't work, is the api image-prompt correct please?

**Comment by konieshadow** [comment]
I'll test it with your pamaters. Wait a minutes.

**Comment by konieshadow** [comment]
Image prompt with "PyraCanny" is ok in my test.

This is my code.

```Python
import base64
import io
import requests
from PIL import Image

url = 'http://127.0.0.1:8888'

img_path = 'D:\\test0005.png'
data = {
"sharpness": 2,
"guidance_scale": 7,
"cn_type1": "PyraCanny",
"prompt": "",
"cn_weight1": 0.6,
"l1": "sd_xl_offset_example-lora_1.0.safetensors",
"image_number": "1",
"base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
"image_seed": -1,
"style_selections": "Fooocus V2,SAI Anime",
"negative_promit": "",
"w1": 0.5,
"refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
"cn_stop1": 0.5,
"aspect_ratios_selection": "1152×896",
"performance_selection": "Quality",
}

response = requests.post(url = f'{url}/v1/generation/image-prompt', json=data, files={"cn_img1": open(img_path, "rb")})
image = Image.open(io.BytesIO(base64.b64decode(response.json()[0]["base64"])))
image.save("d:\\kk.jpg")
```

I just change the parameter "input_image" to "cn_img1".

**Comment by konieshadow** [comment]
test0005.png
![test0005](https://github.com/konieshadow/Fooocus-API/assets/4003217/c30bc5d8-6fd2-40cd-8ce1-54349591f3f0)

kk.png
![kk](https://github.com/konieshadow/Fooocus-API/assets/4003217/ee029c8e-3e87-40a2-a4f0-7d448c6f4637)

**Comment by Kimdow220807** [comment]
> Image prompt with "PyraCanny" is ok in my test.
> 
> This is my code.
> 
> ```python
> import base64
> import io
> import requests
> from PIL import Image
> 
> url = 'http://127.0.0.1:8888'
> 
> img_path = 'D:\\test0005.png'
> data = {
> "sharpness": 2,
> "guidance_scale": 7,
> "cn_type1": "PyraCanny",
> "prompt": "",
> "cn_weight1": 0.6,
> "l1": "sd_xl_offset_example-lora_1.0.safetensors",
> "image_number": "1",
> "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors",
> "image_seed": -1,
> "style_selections": "Fooocus V2,SAI Anime",
> "negative_promit": "",
> "w1": 0.5,
> "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
> "cn_stop1": 0.5,
> "aspect_ratios_selection": "1152×896",
> "performance_selection": "Quality",
> }
> 
> response = requests.post(url = f'{url}/v1/generation/image-prompt', json=data, files={"cn_img1": open(img_path, "rb")})
> image = Image.open(io.BytesIO(base64.b64decode(response.json()[0]["base64"])))
> image.save("d:\\kk.jpg")
> ```
> 
> I just change the parameter "input_image" to "cn_img1".

Thank you. I see.
