### ISSUE TITLE
Very slow compared to fooocus

### ISSUE THREAD

**Issue by colcyber** [mrhan1993/Fooocus-API#144]
hi,
sorry for question,
i tring to to same request (simple testo to image) to fooocus and fooocus-API
but on first, the image returned < 20 seconds, in second case, returno > 5 minutes

probably is my mistake
this is request:

```
params = {
"prompt": "jupiter",
"negative_prompt": "",
"style_selections": [
	"Fooocus V2",
	"Fooocus Photograph",
	#"Fooocus Sharp"
],
"performance_selection": "Speed",
"aspect_ratios_selection": "1152*896",
"image_number": 1,
"image_seed": -1,
"sharpness": 2,
"guidance_scale": 3,
"base_model_name": "realisticStockPhoto_v10.safetensors",
"refiner_model_name": "None",
"refiner_switch": 0.5,
"loras": [
	{
		"model_name": "SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors",
		"weights": 0.1
	}
],
"advanced_params": {
	"adm_scaler_positive": 1.5,
	"adm_scaler_negative": 0.6,
	"adm_scaler_end": 0.3,
	"refiner_swap_method": "joint",
	"adaptive_cfg": 7,
	"sampler_name": "dpmpp_2m_sde_gpu",
	"scheduler_name": "karras",
	"overwrite_step": -1,
	"overwrite_switch": -1,
	"overwrite_width": -1,
	"overwrite_height": -1,
	"overwrite_vary_strength": -1,
	"overwrite_upscale_strength": -1,
	"mixing_image_prompt_and_vary_upscale": False,
	"mixing_image_prompt_and_inpaint": False,
	"debugging_cn_preprocessor": False,
	"skipping_cn_preprocessor": False,
	"controlnet_softness": 0.25,
	"canny_low_threshold": 64,
	"canny_high_threshold": 128,
	"inpaint_engine": "v1",
	"freeu_enabled": False,
	"freeu_b1": 1.01,
	"freeu_b2": 1.02,
	"freeu_s1": 0.99,
	"freeu_s2": 0.95
},
"require_base64": True,
"async_process": True
}

```

thanks for help

**Comment by mrhan1993** [comment]
@colcyber You can follow the command line output to see if you are downloading the model. If not, pay attention to the speed of the progress bar.

**Comment by colcyber** [comment]
> @colcyber You can follow the command line output to see if you are downloading the model. If not, pay attention to the speed of the progress bar.

ye, this is the problem:
fooocus:
[Fooocus Model Management] Moving model(s) has taken 1.08 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [**00:19**<00:00,  1.54it/s]

Fooocus-API
[Fooocus Model Management] Moving model(s) has taken 7.31 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [**11:08**<00:00, 22.30s/it]

bot use GPU at 100%

**Comment by colcyber** [comment]
i'm very sorry.....
restart pc resolved this "issues"
