### ISSUE TITLE
image-prompt接口报错

### ISSUE THREAD

**Issue by vany810** [mrhan1993/Fooocus-API#149]
v0.3.28
图生图接口报错，现在是必须传input_image？以前两张图合成一张图是传cn_image就可以了

**Comment by vany810** [comment]
是不是input_image也要加None判断

**Comment by konieshadow** [comment]
@vany810 刚修复了，一个简单的类型错误。 #150

**Comment by vany810** [comment]
> @vany810 刚修复了，一个简单的类型错误。 #150
@konieshadow 
我看v1版本的接口仍然有报错，v2是修复了

**Comment by mrhan1993** [comment]
@vany810 我这里试的没问题，不过example代码有点问题
