### ISSUE TITLE
windows 一键整合包

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#157]
在windows 开发电脑上想要第一次启动非常复杂， 非常劝退
可以参考Fooocus 项目用python-embed做一个整合包， 减少开发入门门槛

**Comment by konieshadow** [comment]
我有个问题想要先了解下。如果工作中用到了 api 接口，应该是相对专业的使用场景。相对于 Fooocus、WebUI 这种图形化界面，api 一般是面向软件工程师的，而且一般都是要嵌入到一个更大的项目中。我不太理解 windows 一键包的使用场景。

**Comment by aiwillcoming** [comment]
开发的电脑基本上是Win、  开发调试的时候需要跑起来使用本地显卡渲染

**Comment by mrhan1993** [comment]
不如做成 pip 包实在

**Comment by konieshadow** [comment]
> 开发的电脑基本上是Win、 开发调试的时候需要跑起来使用本地显卡渲染

我目前用 wsl2，体验还不错，甚至还可以用到 GPU 的功能内存部分。我是 RTX2060（一台老游戏本），扩到了40G RAM。

**Comment by aiwillcoming** [comment]
重点是一键、下载即用

**Comment by aiwillcoming** [comment]
我可以尝试在release中创建整合包，请添加我为合作者

**Comment by konieshadow** [comment]
> 我可以尝试在release中创建整合包，请添加我为合作者

已添加。

**Comment by aiwillcoming** [comment]
`C:\Fooocus-API>.\python-embed\python.exe Fooocus-API\main.py
Traceback (most recent call last):
  File "C:\Fooocus-API\Fooocus-API\main.py", line 10, in <module>
    from fooocus_api_version import version
ModuleNotFoundError: No module named 'fooocus_api_version'`

不知道是什么问题，我用pip安装时无法正常运行

**Comment by mrhan1993** [comment]
你到 Fooocus-API 目录下执行试试

**Comment by aiwillcoming** [comment]
一样， 各个目录都试了

**Comment by aiwillcoming** [comment]
目前只有在anaconda环境中可以执行， 同样的目录

**Comment by mrhan1993** [comment]
@aiwillcoming main.py 顶部添加 `sys.path.append(os.path.dirname(os.path.realpath(__file__)))`

**Comment by aiwillcoming** [comment]
> @aiwillcoming main.py 顶部添加 `sys.path.append(os.path.dirname(os.path.realpath(__file__)))`

可以了

**Comment by aiwillcoming** [comment]
是否需要提交该行代码

**Comment by mrhan1993** [comment]
@aiwillcoming 提交其实也没什么影响，顺便把65行的 `url = remote_url` 放到57行
![图片](https://github.com/konieshadow/Fooocus-API/assets/50648276/7d5efcb6-cc9e-4ef2-b9f1-fe2ed5c31b83)

**Comment by aiwillcoming** [comment]
@mrhan1993 你来吧
