### ISSUE TITLE
Sometimes bad outputs occurs 

### ISSUE THREAD

**Issue by nickonai** [mrhan1993/Fooocus-API#159]
Hello! thank you how your work again.
After last version update in “fooocus-api” in replicate I see bad output.
Here’s an example for prompt:
“ Night city, view from the rooftop of a skyscraper, a man with a round face and a short haircut, dressed in a futuristic dragon costume, wearing a dragon hat with glowing eyes, realistic city, city lights, futuristic atmosphere”

It occurs not often, and I don’t understand the reason. In few hours I try the same prompt and the problem disappears
![IMG_1952](https://github.com/konieshadow/Fooocus-API/assets/47899541/35b42bba-e8a0-45f9-9468-27b0c1e52303)

**Comment by konieshadow** [comment]
Sorry. I cannot understand the cause of the problem from the underlying principles. I will update the model version as soon as possible.

**Comment by nickonai** [comment]
Thank you, here is the log and screenshot

![Screenshot 2024-01-08 at 12 55 16](https://github.com/konieshadow/Fooocus-API/assets/47899541/9ce0137c-24ad-4e95-9208-a2c05424e4cc)

[Predictor Predict] Params: {'prompt': 'Cute anthropomorphic dog, full-length, tall, wearing a beautiful, puffy dress with long fishnet sleeves and strappy heels, detailed picture, HD', 'negative_prompt': 'nude, naked, censored, nsfw, nipple, genitals, penis, vagina, border, frame, picture frame, logo, text, signature, watermark, copyright', 'style_selections': ['Fooocus V2'], 'performance_selection': 'Speed', 'aspect_ratios_selection': '768*1280', 'image_number': 1, 'image_seed': 283578, 'sharpness': 2.0, 'guidance_scale': 4.0, 'base_model_name': 'juggernautXL_version6Rundiffusion.safetensors', 'refiner_model_name': 'None', 'refiner_switch': 0.5, 'loras': [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ('sdxl_lcm_lora.safetensors', 1.0), ('sdxl_lcm_lora.safetensors', 1.0), ('sdxl_lcm_lora.safetensors', 1.0)], 'uov_input_image': None, 'uov_method': 'Disabled', 'upscale_value': 0, 'outpaint_selections': [], 'outpaint_distance_left': 0, 'outpaint_distance_right': 0, 'outpaint_distance_top': 0, 'outpaint_distance_bottom': 0, 'inpaint_input_image': None, 'inpaint_additional_prompt': '', 'image_prompts': [], 'advanced_params': [False, 1.5, 0.8, 0.3, 7.0, 'dpmpp_2m_sde_gpu', 'karras', False, -1, -1, -1, -1, -1, -1, False, False, False, False, 0.25, 64, 128, 'joint', False, None, None, None, None, False, False, 'v2.6', 1.0, 0.618]}
[Task Queue] Task queue is free, start task, seq=731
[Parameters] Adaptive CFG = 7.0
[Parameters] Sharpness = 2.0
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 283578
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] Cute anthropomorphic dog, full-length, tall, wearing a beautiful, puffy dress with long fishnet sleeves and strappy heels, detailed picture, HD, dramatic light, ambient, sharp focus, appealing, highly detail, rich colors, cool, epic, great composition, dynamic, vibrant, intricate, elegant, pristine, symmetry, fine, artistic, color perfect
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1280, 768)
Preparation time: 0.46 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
  0%|          | 0/30 [00:00<?, ?it/s]
  3%|▎         | 1/30 [00:00<00:06,  4.79it/s]
  7%|▋         | 2/30 [00:00<00:05,  4.79it/s]
 10%|█         | 3/30 [00:00<00:05,  4.81it/s]
 13%|█▎        | 4/30 [00:00<00:05,  4.82it/s]
 17%|█▋        | 5/30 [00:01<00:05,  4.81it/s]
 20%|██        | 6/30 [00:01<00:05,  4.79it/s]
 23%|██▎       | 7/30 [00:01<00:04,  4.78it/s]
 27%|██▋       | 8/30 [00:01<00:04,  4.77it/s]
 30%|███       | 9/30 [00:01<00:04,  4.75it/s]
 33%|███▎      | 10/30 [00:02<00:04,  4.76it/s]
 37%|███▋      | 11/30 [00:02<00:03,  4.77it/s]
 40%|████      | 12/30 [00:02<00:03,  4.79it/s]
 43%|████▎     | 13/30 [00:02<00:03,  4.78it/s]
 47%|████▋     | 14/30 [00:02<00:03,  4.81it/s]
 50%|█████     | 15/30 [00:03<00:03,  4.83it/s]
 53%|█████▎    | 16/30 [00:03<00:02,  4.85it/s]
 57%|█████▋    | 17/30 [00:03<00:02,  4.87it/s]
 60%|██████    | 18/30 [00:03<00:02,  4.87it/s]
 63%|██████▎   | 19/30 [00:03<00:02,  4.88it/s]
 67%|██████▋   | 20/30 [00:04<00:02,  4.89it/s]
 70%|███████   | 21/30 [00:04<00:01,  4.90it/s]
 73%|███████▎  | 22/30 [00:04<00:01,  4.90it/s]
 77%|███████▋  | 23/30 [00:04<00:01,  4.91it/s]
 80%|████████  | 24/30 [00:04<00:01,  4.91it/s]
 83%|████████▎ | 25/30 [00:05<00:01,  4.92it/s]
 87%|████████▋ | 26/30 [00:05<00:00,  4.92it/s]
 90%|█████████ | 27/30 [00:05<00:00,  4.91it/s]
 93%|█████████▎| 28/30 [00:05<00:00,  4.91it/s]
 97%|█████████▋| 29/30 [00:05<00:00,  4.93it/s]
100%|██████████| 30/30 [00:06<00:00,  4.95it/s]
100%|██████████| 30/30 [00:06<00:00,  4.86it/s]
Image generated with private log at: /src/repositories/Fooocus/outputs/2024-01-08/log.html
Generating and saving time: 6.64 seconds
Clean task history, remove task: 631
[Task Queue] Finish task, seq=731
[Predictor Predict] Finished with 1 images"

**Comment by NicolasRoehm** [comment]
I have exactly the same problem which appears on my custom model after a certain number (around 15 close predictions) of generated images, the quality drops dramatically

**Comment by merijnvanes** [comment]
I can replicate this. First run on the `Speed` setting a couple of times and all goes well. Then switch to `Extreme Speed`, the first time it gives back an OK result, the second time however, it yields a wrong one and it gets gradually worse each run.
```
import replicate

API = replicate.Client(api_token="REPLICATE_API_TOKEN")

output = API.run(
    "konieshadow/fooocus-api-realistic:8958d6f677f825b57175bf644471fddfee6210a165cc20037323575a84d16afb",
    input={
        "prompt": "cow",
        "image_seed": 6091967260935476000,
        "image_number": 1,
        "style_selections": "Fooocus V2,Fooocus Photograph,Fooocus Negative",
        "performance_selection": "Speed", # This goes well
        # "performance_selection": "Extreme Speed", # This goes wrong the second time and gets worse thereafter
    }
)
print(output)
```

**Comment by konieshadow** [comment]
An unexpected error. When using 'Extreme Speed', the 'sdxl_lcm_lora' was added to default_loras (global variable) over and over.

**Comment by konieshadow** [comment]
Just updated the replicate models. Sorry for that.

**Comment by NicolasRoehm** [comment]
I tried your fix, with 25 images and everything is fine! 👍

**Comment by merijnvanes** [comment]
You're awesome! Thank you @konieshadow

**Comment by nickonai** [comment]
Thanks, it works fine
