### ISSUE TITLE
Hope to add an interface to view task progress (progress bar)

### ISSUE THREAD

**Issue by pengpengzi** [mrhan1993/Fooocus-API#16]
First of all, this is a great project, and I appreciate your work. I have tested all the interfaces and they work properly. I was wondering if it would be possible to add a progress bar viewing interface so that I could know the progress of my tasks in the frontend.

**Comment by konieshadow** [comment]
Good idea. What do you think about splitting an genraration api into two parts?

The first one is used to submit tasks, asynchronously, and returns the task id directly after the request.

The second one is used to request task information and can obtain task progress and results.

**Comment by konieshadow** [comment]
@pengpengzi Can I ask which type of frontend are you buiding? I could make this project more useful if I know how people want to use it.

**Comment by pengpengzi** [comment]
> @pengpengzi Can I ask which type of frontend are you buiding? I could make this project more useful if I know how people want to use it.
I'm sorry for not seeing your message in time. Specifically, in the backend, I deployed four API services on two A40 graphics cards and implemented load balancing to handle the queuing issues of multiple users. In the frontend, I called both the SD API and the official Midjourney API simultaneously. The challenge here is how to better handle the multi-task queuing problem with limited GPU resources. Currently, I am also looking for suitable methods and modifying the calling logic.

**Comment by pengpengzi** [comment]
> Good idea. What do you think about splitting an genraration api into two parts?
> 
> The first one is used to submit tasks, asynchronously, and returns the task id directly after the request.
> 
> The second one is used to request task information and can obtain task progress and results.

Yes！ this way users can clearly know their progress and how much longer it will take. You know, making users wait without any indication is a very frustrating thing.

**Comment by konieshadow** [comment]
Alreay add basic "async job" support for image generation request.

**Comment by pengpengzi** [comment]
nice work
