### ISSUE TITLE
建议使用语义化版本号

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#166]
https://semver.org/lang/zh-CN/

版本格式：主版本号.次版本号.修订号，版本号递增规则如下：

主版本号：当你做了不兼容的 API 修改，
次版本号：当你做了向下兼容的功能性新增，
修订号：当你做了向下兼容的问题修正。

简而言之就是当发生API变更时需要增加次版本号或主版本号， 仅当做bug修改或性能优化等API完全兼容的改动时才只增加修订号
当前的版本号规则体现不出这一点，经常发生破坏变更而下游人员难以感知

**Comment by mrhan1993** [comment]
@aiwillcoming 你该不会是个产品经理吧 :joy:

**Comment by aiwillcoming** [comment]
人人都是产品经理

**Comment by konieshadow** [comment]
目前的版本号风格其实是学Fooocus的，确实不太科学。
