### ISSUE TITLE
memory usage anomaly，It feels like the memory isn't being released.

### ISSUE THREAD

**Issue by xplfly** [mrhan1993/Fooocus-API#17]
command：python main.py --port 5001

<img width="1515" alt="截屏2023-10-13 18 03 22" src="https://github.com/konieshadow/Fooocus-API/assets/31639097/017d485e-acfa-46be-904d-73404001eb74">

> 

Fooocus-API：process id -60290
Fooocus：process id-2406

<img width="568" alt="截屏2023-10-13 17 57 31" src="https://github.com/konieshadow/Fooocus-API/assets/31639097/21903db5-a319-4205-a696-a3eaa7369fcd">

**Comment by konieshadow** [comment]
Thank you for feedbak. I'll try to fix it when merging the latest version Fooocus code.

**Comment by konieshadow** [comment]
In my tests, I didn't find that the gpu memory will continue to increase after each generation of images, but will be released before each generation.

This processing should be exactly the same as Fooocus. I haven't checked the specific code, but the gpu memory allocation may be related to the total available gpu memory.

Sorry for than. If you encounter gpu memory exhaustion, please continue to report.

**Comment by xplfly** [comment]
in my tests, gpu memory higher then fooocus

the same request info:
`
   "prompt": "modern living room",
   "image_number": 1
`

## fooocus-api (gpu server A)
<img width="2484" alt="截屏2023-10-17 15 44 13" src="https://github.com/konieshadow/Fooocus-API/assets/31639097/d18f202e-35fa-4e2c-be8d-3f07afe286c7">

## fooocus + FastAPI (gpu server B）；fooocus + FastAPI，fooocus-API（gpu server B）
14:17  process：fooocus + FastAPI
14:24 process：fooocus + FastAPI；fooocus-API
<img width="602" alt="截屏2023-10-17 16 28 52" src="https://github.com/konieshadow/Fooocus-API/assets/31639097/812a9bc5-a9b5-4bcf-ac2d-ab5e52d16f7c">

**Comment by xplfly** [comment]
now is right，I'll run some more batch tests.

process: 114010
<img width="629" alt="截屏2023-10-17 20 25 21" src="https://github.com/konieshadow/Fooocus-API/assets/31639097/366d335a-31e7-40a8-855f-b05076b29204">
