### ISSUE TITLE
如何支持多显卡？

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#170]
单台机器上插了4张显卡，但是好像只会用到一张卡

**Comment by mrhan1993** [comment]
@aiwillcoming 你的设备倒是牛批，我都没见过多显卡设备  :joy:

**Comment by aiwillcoming** [comment]
租的

**Comment by aiwillcoming** [comment]
云服务器厂商租一下很便宜

**Comment by aiwillcoming** [comment]
看了下 fooocus 多显卡支持还在开发中
那能否暂时先在启动时指定显卡
@mrhan1993

**Comment by mrhan1993** [comment]
`--gpu-device-id DEVICE_ID` 参数试一下。

**Comment by aiwillcoming** [comment]
https://github.com/lllyasviel/Fooocus/issues/1034

**Comment by aiwillcoming** [comment]
Worker error: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by aiwillcoming** [comment]
```
Worker error: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

**Comment by p971607** [comment]
6

**Comment by mrhan1993** [comment]
set the system environment argument `CUDA_VISIBLE_DEVICES=0` before launch
