### ISSUE TITLE
error after latest version

### ISSUE THREAD

**Issue by bsormagec** [mrhan1993/Fooocus-API#173]
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
I am getting this error after pull sqlite version I don't know is it related but after pull I see that.

**Comment by mrhan1993** [comment]
It will not affect the use, and it will not be because of our update. this is a package in Linux, windows prebuild version can find [here](https://huggingface.co/r4ziel/xformers_pre_built/blob/main/triton-2.0.0-cp310-cp310-win_amd64.whl) 
if you care about this error.
