### ISSUE TITLE
Deploying Fooocus-API on Replicate with Custom Checkpoint

### ISSUE THREAD

**Issue by NicolasRoehm** [mrhan1993/Fooocus-API#174]
Hello @KonieShadow,

Firstly, thank you for the fantastic work done!

I'm seeking clarification on how you deployed a version of Fooocus-API with a custom preset, like you did for [fooocus-api-anime](https://replicate.com/konieshadow/fooocus-api-anime) or [fooocus-api-realistic](https://replicate.com/konieshadow/fooocus-api-realistic), on the Replicate site.

I've managed to load the project locally, create my own "preset", and use it through the command:

```cmd
~/Fooocus-API/repositories/Fooocus$ python3 entry_with_update.py --preset myOwnPreset
```

However, when I attempt:

```cmd
~/Fooocus-API$ cog predict -i prompt='1 girl',preset='myOwnPreset'
```
The Docker image starts with: `Loaded preset: /src/presets/anime.json`

How can I deploy Fooocus-API on Replicate but with my own checkpoint? :)
Thanks in advance for your help!

Best regards,
Nicolas

**Comment by xiyouZ** [comment]
Greeting, if you want to change the model of API, you could try edit value " default_base_model_name = 'juggernautXL_version6Rundiffusion.safetensors'  "in file Fooocus-API\fooocusapi\parameters.py which would load juggernautXL_version6Rundiffusion.safetensors at folder Fooocus-API\repositories\Fooocus\models\checkpoints. when it needs to load.

**Comment by NicolasRoehm** [comment]
Thank you very much for your help @xiyouZ!
I was able to deploy my own model to Replicate <3

**Comment by jakelauer** [comment]
For anyone else who finds this, that setting now lives in `fooocusapi/configs/default.py`
