### ISSUE TITLE
建议默认监听 0.0.0.0

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#178]

**Comment by mrhan1993** [comment]
没必要，从安全角度讲也是不应该的。

**Comment by aiwillcoming** [comment]
安全是防火墙做的事， 且api就是需要开放调用服务

**Comment by mrhan1993** [comment]
当他配置 `--host 0.0.0.0` 的时候，他知道自己在做什么。不是我们给他做这个决定。

**Comment by aiwillcoming** [comment]
大部分人不知道如何配置

**Comment by mrhan1993** [comment]
用来限制不懂的人的权限。当然，你要认真讲起来，其实也无所谓。不过我依然不推荐如此

**Comment by konieshadow** [comment]
安全永远是第一位的。该项目暴露的接口没有鉴权，暴露在公网很容易被人利用。且项目依赖众多，保不齐哪一步有严重的漏洞。
比较合理的使用方式是仅在 127.0.0.1 和 VPC 内网暴露端口。
