### ISSUE TITLE
I really need this. I wonder if the author has a communication group?

### ISSUE THREAD

**Issue by 812913329** [mrhan1993/Fooocus-API#18]
The official API does not support http. I originally wanted to use 111's webui, but in comparison, the image quality is better than fooocus. So I decided to adopt this

**Comment by 812913329** [comment]
The official has added the image fusion function, 10-15

**Comment by konieshadow** [comment]
@812913329 Given the current number of users of this project, I don't see the need to create a developer community at this time. I am not an AI or Python expert myself. I am afraid that it is difficult for the component community to maintain effective activity at present.
However, you can still ask any relevant technical questions here and I will try to answer them.

**Comment by konieshadow** [comment]
> The official has added the image fusion function, 10-15

I didn't find anything related to "image fusion". Can you point out which feature it is?

**Comment by 812913329** [comment]
> > 官方增加了图像融合功能，10-15
> 
> 我没有找到任何与“图像融合”相关的内容。你能指出它是哪个功能吗？
这个功能，我好像没在api里面看到有
![Screenshot_20231016-152532](https://github.com/konieshadow/Fooocus-API/assets/67380983/d15ff87f-f3c8-4ad3-a128-9d3be26c5099)

**Comment by 812913329** [comment]
I just checked fooocus's project update log, but she didn't seem to write out the update for this feature. If you can’t find it, I’ll check it out when I get home and send it to you.

**Comment by konieshadow** [comment]
> > > 官方增加了图像融合功能，10-15
> > 
> > 
> > 我没有找到任何与“图像融合”相关的内容。你能指出它是哪个功能吗？
> > 这个功能，我好像没在api里面看到有
> > ![Screenshot_20231016-152532](https://github.com/konieshadow/Fooocus-API/assets/67380983/d15ff87f-f3c8-4ad3-a128-9d3be26c5099)

Fooocus-API 已经添加了对 Image Prompt 的支持，接口是 POST /v1/generation/image-prompt，请启动后转到 http://127.0.0.1:8888/docs 查看接口文档。

**Comment by 812913329** [comment]
> > > > 官方增加了图像融合功能，10-15
> > > 
> > > 
> > > 我没有找到任何与“图像融合”相关的内容。你能指出它是哪个功能吗？
> > > 这个功能，我想在api里面没有看到
> > > ![截图_20231016-152532](https://github.com/konieshadow/Fooocus-API/assets/67380983/d15ff87f-f3c8-4ad3-a128-9d3be26c5099)
> 
> Fooocus-API 已经添加了对 Image Prompt 的支持，接口是 POST /v1/ Generation/image-prompt，请启动后转到http://127.0.0.1:8888/docs查看接口文档。

Great, my boss! The update is good and fast. I'm not sure if it's possible to add an API for obtaining models and character models, as it's okay to use them locally or on your own. If using cloud for others, it will be inconvenient to call other models because there is no model list. Of course, you can actually write a separate service return model list exe yourself, but I still think integrating it into a big guy's project is more suitable. 2: Big shots may have considered using Linux at the beginning of their writing, but installation is not very friendly to Windows. If you want to package the program for someone else to open and use it directly, it is not very convenient. But there seems to be no better way to package this. If you want to use it for others, it seems that the best way is to package the installed virtual environment together with py. It's too troublesome to compare environmental issues

**Comment by konieshadow** [comment]
Good suggestion, I could add an api to expose the locally available list of models.

Regarding Windows support, although I am using Windows for development, my laptop only has a poor 6G. I might rent a windows GPU server.

**Comment by 812913329** [comment]
> 好建议，我可以添加一个 api 来公开本地可用的模型列表。
> 
> 关于Windows支持，虽然我使用Windows进行开发，但我的笔记本电脑只有可怜的6G。我可能会租一台 Windows GPU 服务器。



> 好建议，我可以添加一个 api 来公开本地可用的模型列表。
> 
> 关于Windows支持，虽然我使用Windows进行开发，但我的笔记本电脑只有可怜的6G。我可能会租一台 Windows GPU 服务器。

Oh my gosh? But I hope what you're referring to is the VRAM of the graphics card, not the RAM, haha. No big deal, I'm currently working on a project based on GPT and fooocus. If it makes money, I'll come back to upgrade your laptop. Although I feel like I'll have to work for a few more months and end up with nothing, your fooocus API has been a great help to me. I was originally using the SD web UI from the 111 expert, but the image quality from fooocus is just too good. So, I decided to give up and choose fooocus, although I also considered comfyui. I just don't know why they don't provide an HTTP API. For someone like me who hasn't learned Python, it's really hard to wrap it myself.

At present, there are not many people using fooocus, and it seems that there are even fewer people using the fooocus api project.
