### ISSUE TITLE
无法更换模型

### ISSUE THREAD

**Issue by illusiona** [mrhan1993/Fooocus-API#181]
params = {
    "prompt": "轻奢风格的客厅,qingshe",
    "negative_prompt": "",
    "style_selections": [
        "Fooocus V2",
        "Fooocus Enhance",
        "Fooocus Sharp"
    ],
    "performance_selection": "Quality",
    "aspect_ratios_selection": "1152*896",
    "image_number": 1,
    "image_seed": -1,
    "sharpness": 2,
    "guidance_scale": 4,
    "base_model_name": r"Actual_Texture_ZY_SDXL_V2.3.safetensors",
    "refiner_model_name": "None",
    "refiner_switch": 0.9,
    "loras": [
        {
            "model_name": "qinshe.safetensors",
            "weight": 0.8
        }
    ],
}
请求参数如上，文件中已经有该模型与loras，但是无法通过base_model_name 和model_name导入这两个模型
已试去文件后缀，加上路径但都无法加载模型。通过从fastapi上模拟的入参也无法达到更换模型的效果

错误信息如下
[Warning] Wrong base_model_name input: Actual_Texture_ZY_SDXL_V2.3.safetensors, using default
[Warning] Wrong lora model_name input: qinshe.safetensors, using 'None'

**Comment by aiwillcoming** [comment]
刷新一下，不行就重启一下

**Comment by konieshadow** [comment]
@illusiona 调用 `/v1/engines/refresh-models` 接口，返回结果中有该模型吗？

**Comment by konieshadow** [comment]
@illusiona 确保模型文件的路径和根目录下 config.txt 中的 "path_checkpoints" 配置项一致。

**Comment by illusiona** [comment]
> @illusiona 调用 `/v1/engines/refresh-models` 接口，返回结果中有该模型吗？

v1接口也不行，没有显示该模型，path_checkpoints配置和模型路径是一致的

**Comment by illusiona** [comment]
![Uploading path.png…]()

**Comment by illusiona** [comment]
将模型参数换为其他默认模型成功，但是导入非默认模型的第三方模型则会导入失败

**Comment by konieshadow** [comment]
从代码上来看，refresh-models 扫描模型只会判断模型文件的路径和后缀名（'.pth', '.ckpt', '.bin', '.safetensors', '.fooocus.patch'），不会校验模型文件的内容。
