### ISSUE TITLE
Can anyone help me out

### ISSUE THREAD

**Issue by YellowTigerr** [mrhan1993/Fooocus-API#185]
![屏幕截图 2024-01-22 093934](https://github.com/konieshadow/Fooocus-API/assets/137086083/753b075a-d851-403d-a876-1c60fa6181f8)
![屏幕截图 2024-01-22 094029](https://github.com/konieshadow/Fooocus-API/assets/137086083/ad488bf6-fd35-4eaa-8c5c-a785477f57a8)
INFO:     192.168.40.111:61130 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.40.111:61130 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     192.168.40.111:57650 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.40.111:57650 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.40.111:57650 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.40.111:58830 - "GET / HTTP/1.1" 200 OK

**Comment by konieshadow** [comment]
@YellowTigerr Didn't see anything unusual.

**Comment by konieshadow** [comment]
Closed due to insufficient information.
