### ISSUE TITLE
需求 设置 禁用访问日志

### ISSUE THREAD

**Issue by aiwillcoming** [mrhan1993/Fooocus-API#186]
增加启动参数 --no-access-log 以仅禁用访问日志，不更改日志级别。

**Comment by mrhan1993** [comment]
什么意思？

**Comment by aiwillcoming** [comment]
INFO:   6:60826 - "GET /ping HTTP/1.1" 200 OK
INFO:      40:46532 - "GET /ping HTTP/1.1" 200 OK
INFO:  :46536 - "GET /ping HTTP/1.1" 200 OK

uvicorn 的访问日志，刷太多了

**Comment by mrhan1993** [comment]
你把 `api.py` 最后的启动函数改成下边的试试。
```python
def start_app(arguments):
    file_utils.static_serve_base_url = arguments.base_url + "/files/"
    uvicorn.run(app="fooocusapi.api:app", host=arguments.host,
                port=arguments.port, log_level=arguments.log_level, access_log=False)
```
但这个应该会关掉所有 `access log`，至于更加细致的日志控制，等我研究研究。

**Comment by aiwillcoming** [comment]
加一个启动参数，其实大部分情况下 access log 没什么用

**Comment by mrhan1993** [comment]
谁家服务器会关掉access log啊。你别瞎搞

**Comment by aiwillcoming** [comment]
一般外面还有一层nginx, 那里有更好的access log

**Comment by aiwillcoming** [comment]
可选控制就好
