### ISSUE TITLE
能不能制作成bat脚本一键快捷安装呢

### ISSUE THREAD

**Issue by 812913329** [mrhan1993/Fooocus-API#19]
能不能制作成bat脚本一键快捷安装呢

**Comment by konieshadow** [comment]
起初我是假定想使用 Fooocus 并暴露 API 的用户通常会使用 Linux 服务器，现在看来确实还有很多 Windows 平台的使用需求。我会试着写个 bat 一键安装脚本，或者像 Fooocus 官方一样出个解压即可用的压缩包。你知道在中国大陆网络也是一个麻烦的问题。

感谢反馈意见。

**Comment by ImmNaruto** [comment]
我这里本地测试了下，Windows的安装教程如下，提供一个参考：
参考配置：
Windows 11+Pycharm+Anaconda
Fooocus版本：2.1.679
Fooocus-API版本: 0.1.17
方法步骤：
1.下载Fooocus项目并解压
2.git clone Fooocus-API项目，将fooocus_api_version.py，main.py，predict.py，requirements.txt这几个文件和docs，fooocapi两个文件夹放入Fooocus项目的Fooocus文件夹下，如图
![image](https://github.com/konieshadow/Fooocus-API/assets/74526577/7ba3034f-1571-4394-bdd4-cba943d797cb)
3.conda配置环境，pip install -r requirements.txt requirements_versions.txt
4.在pycharm中将Fooocus/backend/headless这个文件夹设为源代码根目录，如图
![image](https://github.com/konieshadow/Fooocus-API/assets/74526577/b99259cb-e2cd-4f55-a4d4-0b86a048efa2)
5.pycharm中右键main.py运行即可，建议将sync-repo默认值修改为skip（版本稳定性考虑）
![image](https://github.com/konieshadow/Fooocus-API/assets/74526577/596fec67-7b8a-49c0-b8e0-c0c0596b4e09)
即可成功运行
最后，感谢大佬做的这个API项目，非常棒！

**Comment by 812913329** [comment]
> 我这里本地测试了下，Windows的安装教程如下，提供一个参考： 参考配置： Windows 11+Pycharm+Anaconda Fooocus版本：2.1.679 Fooocus-API版本: 0.1.17 方法步骤： 1.下载Fooocus项目并解压 2.git clone Fooocus-API项目，将fooocus_api_version.py，main.py，predict.py，requirements.txt这几个文件和docs，fooocapi两个文件夹放入Fooocus项目的Fooocus文件夹下，如图 ![image](https://user-images.githubusercontent.com/74526577/275705776-7ba3034f-1571-4394-bdd4-cba943d797cb.png) 3.conda配置环境，pip install -r requirements.txt requirements_versions.txt 4.在pycharm中将Fooocus/backend/headless这个文件夹设为源代码根目录，如图 ![image](https://user-images.githubusercontent.com/74526577/275706258-b99259cb-e2cd-4f55-a4d4-0b86a048efa2.png) 5.pycharm中右键main.py运行即可，建议将sync-repo默认值修改为skip（版本稳定性考虑） ![image](https://user-images.githubusercontent.com/74526577/275706568-596fec67-7b8a-49c0-b8e0-c0c0596b4e09.png) 即可成功运行 最后，感谢大佬做的这个API项目，非常棒！

Win直接在虚拟环境安装就行，主要是集成环境给我用户方便一键使用。目前已经算是解决，通过py打包，用户解压直接即可成功运行。不过没想到还能遇到国内的人

**Comment by ImmNaruto** [comment]
> > 我这里本地测试了下，Windows的安装教程如下，提供一个参考： 参考配置： Windows 11+Pycharm+Anaconda Fooocus版本：2.1.679 Fooocus-API版本: 0.1.17 方法步骤： 1.下载Fooocus项目并解压 2.git clone Fooocus-API项目，将fooocus_api_version.py，main.py，predict.py，requirements.txt这几个文件和docs，fooocapi两个文件夹放入Fooocus项目的Fooocus文件夹下，如图 ![image](https://user-images.githubusercontent.com/74526577/275705776-7ba3034f-1571-4394-bdd4-cba943d797cb.png) 3.conda配置环境，pip install -r requirements.txt requirements_versions.txt 4.在pycharm中将Fooocus/backend/headless这个文件夹设为源代码根目录，如图 ![image](https://user-images.githubusercontent.com/74526577/275706258-b99259cb-e2cd-4f55-a4d4-0b86a048efa2.png) 5.pycharm中右键main.py运行即可，建议将sync-repo默认值修改为skip（版本稳定性考虑） ![image](https://user-images.githubusercontent.com/74526577/275706568-596fec67-7b8a-49c0-b8e0-c0c0596b4e09.png) 即可成功运行 最后，感谢大佬做的这个API项目，非常棒！
> 
> Win直接在虚拟环境安装就行，主要是集成环境给我用户方便一键使用。目前已经算是解决，通过py打包，用户解压直接即可成功运行。不过没想到还能遇到国内的人

了解，用户一键使用api也是个好想法。不过我这是用来本地调试或者自定义api的，所以就顺手写了个。github上国内开发者也挺多的。

**Comment by 812913329** [comment]
> > > 我在这里本地测试教程了下，Windows的安装如下，提供一个参考： 参考配置： Windows 11+Pycharm+Anaconda Fooocus版本：2.1.679 Fooocus-API版本: 0.1.17 方法步骤： 1.下载Fooocus项目并解压2.git clone Fooocus-API项目，将fooocus_api_version.py，main.py，predict.py，requirements.txt这几个文件和docs，fooocapi两个文件夹放入Fooocus项目的Fooocus文件夹下，如图![图像](https://user-images.githubusercontent.com/74526577/275705776-7ba3034f-1571-4394-bdd4-cba943d797cb.png)3 .conda配置环境，pip install -rrequirements.txtrequirements_versions.txt 4.在pycharm中将Fooocus/backend/headless这个文件夹设为源代码根目录，如图![图像](https://user-images.githubusercontent.com/74526577/275706258-b99259cb-e2cd-4f55-a4d4-0b86a048efa2.png)5.pycharm中右键main.py运行即可，建议修改sync-repo默认值为skip（版本稳定性考虑）![图像](https://user-images.githubusercontent.com/74526577/275706568-596fec67-7b8a-49c0-b8e0-c0c0596b4e09.png)最后即可成功运行，感谢大佬做的这个API项目，打赏！
> > 
> > 
> > win直接在虚拟环境安装就可以了，主要是集成环境给我用户方便一键使用。目前已经解决了，通过py文件夹，用户解压直接就可以成功运行。不过居然还能遇到国内的人
> 
> 了解了，用户一键使用api也是不错的想法。不过我是用来本地调试或者自定义api的，所以就顺手写了个。github上国内开发者也挺多的。

自定义api？厉害了，可惜我不会py以及gradio。给我源码都用不了，只能靠大佬更新

**Comment by pengpengzi** [comment]
> > > > 我在这里本地测试教程了下，Windows的安装如下，提供一个参考： 参考配置： Windows 11+Pycharm+Anaconda Fooocus版本：2.1.679 Fooocus-API版本: 0.1.17 方法步骤： 1.下载Fooocus项目并解压2.git clone Fooocus-API项目，将fooocus_api_version.py，main.py，predict.py，requirements.txt这几个文件和docs，fooocapi两个文件夹放入Fooocus项目的Fooocus文件夹下，如图![图像](https://user-images.githubusercontent.com/74526577/275705776-7ba3034f-1571-4394-bdd4-cba943d797cb.png)3 .conda配置环境，pip install -rrequirements.txtrequirements_versions.txt 4.在pycharm中将Fooocus/backend/headless这个文件夹设为源代码根目录，如图![图像](https://user-images.githubusercontent.com/74526577/275706258-b99259cb-e2cd-4f55-a4d4-0b86a048efa2.png)5.pycharm中右键main.py运行即可，建议修改sync-repo默认值为skip（版本稳定性考虑）![图像](https://user-images.githubusercontent.com/74526577/275706568-596fec67-7b8a-49c0-b8e0-c0c0596b4e09.png)最后即可成功运行，感谢大佬做的这个API项目，打赏！
> > > 
> > > 
> > > win直接在虚拟环境安装就可以了，主要是集成环境给我用户方便一键使用。目前已经解决了，通过py文件夹，用户解压直接就可以成功运行。不过居然还能遇到国内的人
> > 
> > 
> > 了解了，用户一键使用api也是不错的想法。不过我是用来本地调试或者自定义api的，所以就顺手写了个。github上国内开发者也挺多的。
> 
> 自定义api？厉害了，可惜我不会py以及gradio。给我源码都用不了，只能靠大佬更新

你可以试试fooocus提供的一键包，更改run.bat的启动文件为main.py,这两者的区别不大，但是安装依赖包要翻墙才能顺利安装

**Comment by pengpengzi** [comment]
The specific operation can be to take the run.bat and python_embedded from the one-click package provided by fooocus and place them in the same directory as the main.py of this project. Open run.bat with Notepad and replace the directory of the .py file with the directory of main.py.
![图片](https://github.com/konieshadow/Fooocus-API/assets/103752028/4d3a2c87-b41f-4480-a901-91277c23fb32)

**Comment by 812913329** [comment]
的确可以，但是目前我还差点像fooocus那样不用自己安装环境集成环境，点击bat就能启动的方式，目前我的解决方式是通过py打包虚拟环境，会生成一个fooocus api的exe程序，也能不用安装环境就能一键启动。但是不懂，为什么必须得是exe，不能像bat那样脚本运行呢
