### ISSUE TITLE
求助：30个生图任务，每次完成3个task，就自动停止了，后台日志没报错，但python报错JSONDecodeError

### ISSUE THREAD

**Issue by mjn404** [mrhan1993/Fooocus-API#193]

**Comment by konieshadow** [comment]
@mjn404 你在用最新版本的代码吗？我需要更多的信息比如错误日志才能分析原因。

**Comment by mjn404** [comment]
> @mjn404 你在用最新版本的代码吗？我需要更多的信息比如错误日志才能分析原因。
我用的最新版的Fooocus的config.txt。CLI中没有报错，python中有报错。
![image](https://github.com/konieshadow/Fooocus-API/assets/57367960/2ddf8ef7-71f6-4ab8-9b7b-2d462da1d06d)
![image](https://github.com/konieshadow/Fooocus-API/assets/57367960/9d467c13-38c1-4d8e-a4a6-ea25cb18cca2)
![image](https://github.com/konieshadow/Fooocus-API/assets/57367960/2c573951-b2db-4b4c-813b-ee4543df0666)
![image](https://github.com/konieshadow/Fooocus-API/assets/57367960/74989985-1b3f-47cf-b05a-2a5ccc408440)

**Comment by konieshadow** [comment]
我知道问题的原因了，我会先提交一个简单的修复版本，后面再从更底层解决问题。

**Comment by mrhan1993** [comment]
> 我知道问题的原因了，我会先提交一个简单的修复版本，后面再从更底层解决问题。

最简单的把队列调大就可以了。这个是超出队列的返回的是错误，我的示例里没有对这些做额外处理，所以会这样

**Comment by mrhan1993** [comment]
@konieshadow api.py 77行 seed改成str类型。我先提交了？

**Comment by konieshadow** [comment]
> > 我知道问题的原因了，我会先提交一个简单的修复版本，后面再从更底层解决问题。
> 
> 最简单的把队列调大就可以了。这个是超出队列的返回的是错误，我的示例里没有对这些做额外处理，所以会这样

目前有两个问题：
1. 异步请求遇到队列超出限制后返回的数据结构不理想；
2. 没有完善的任务队列机制，仅靠线程池无法支持大量的任务队列。

**Comment by konieshadow** [comment]
> @konieshadow api.py 77行 seed改成str类型。我先提交了？

先别，我也在改这一块儿。

**Comment by mrhan1993** [comment]
@konieshadow 好

**Comment by konieshadow** [comment]
我先整理下 api_utils.py generation_output 方法，然后准备引入一个任务队列，比如 celery。

**Comment by mjn404** [comment]
这次没有报错，还只完成3任务就停止。
![image](https://github.com/konieshadow/Fooocus-API/assets/57367960/4161585e-6554-4eb7-ad86-e4aa5ce3b4c6)

**Comment by mrhan1993** [comment]
@mjn404 你拉的最新版吗？

**Comment by mjn404** [comment]
> @mjn404 你拉的最新版吗？

是的吧， 我只替换了最新版的三个.py文件。

**Comment by mrhan1993** [comment]
@mjn404 启动的时候指定 `--queue-size 100`或者更大的数，另外一个更新还没合并。

**Comment by konieshadow** [comment]
@mjn404 生成图片的接口是不支持并发的，无论怎样都是要等一个个执行，不知道你的具体需求是怎样的。

**Comment by mjn404** [comment]
> @mjn404 生成图片的接口是不支持并发的，无论怎样都是要等一个个执行，不知道你的具体需求是怎样的。
30个任务就完成了3个任务就停止。 需求很简单，批量一个个运行完成就行，不需要并发。

**Comment by mrhan1993** [comment]
@konieshadow 默认100的更新在dev呢，现在还是三个。他指定个queue_size就好了

**Comment by konieshadow** [comment]
> > @mjn404 生成图片的接口是不支持并发的，无论怎样都是要等一个个执行，不知道你的具体需求是怎样的。
> > 30个任务就完成了3个任务就停止。 需求很简单，批量一个个运行完成就行，不需要并发。

你可以先切到 dev 分支测试下。

**Comment by xinjiguaike** [comment]
> 我先整理下 api_utils.py generation_output 方法，然后准备引入一个任务队列，比如 celery。

请问这个celery有在支持了吗，我现在是分布式部署的这个服务，没有持久化的任务队列，没办法保证任务被可靠的执行

**Comment by xinjiguaike** [comment]
> > 我先整理下 api_utils.py generation_output 方法，然后准备引入一个任务队列，比如 celery。
> 
> 请问这个celery有在支持了吗，我现在是分布式部署的这个服务，没有持久化的任务队列，没办法保证任务被可靠的执行

@konieshadow

**Comment by mrhan1993** [comment]
@xinjiguaike 我的建议是基于现有的程序用 celery 套个壳。尽管我确实有一支持 celery 的旧版。
