### ISSUE TITLE
No gpu device id cmd to set which gfx card to use? [--gpu-device-id DEVICE_ID]

### ISSUE THREAD

**Issue by Teedo145** [mrhan1993/Fooocus-API#207]
Is it possible? I can find it in fooocus but not fooocus api?

**Comment by konieshadow** [comment]
> Is it possible? I can find it in fooocus but not fooocus api?

Fooocus-API support all Fooocus's cmd flags, so you can use it.

**Comment by Teedo145** [comment]
Thanks I'll try again...it wasn't in the command arguments and it said it was an invalid argument when I tried but I'll try again when I get home

**Comment by mrhan1993** [comment]
@Teedo145 
![图片](https://github.com/konieshadow/Fooocus-API/assets/50648276/906bc951-5a32-445c-a526-1bc60fb40619)

is ok for me, you can pull the latest version and try again.
