### ISSUE TITLE
update to juggernautXL_8 

### ISSUE THREAD

**Issue by bachgroup** [mrhan1993/Fooocus-API#209]
Hey Konieshadow, 

Thank a lot for your work. Can you please update your model on replicate with  juggernautXL_v8Rundiffusion (https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors) please ? 

Because the inpaint mode on the eyes isn t so good compare to the one in Fooocus Google Colab.

Thank a lot Konieshadow and great work for this API

**Comment by konieshadow** [comment]
Sorry. I'm on a busy vacation. Maybe a week later.
