### ISSUE TITLE
Due to eye disease, updates may have to be stopped for a while. I’m very sorry.

### ISSUE THREAD

**Issue by konieshadow** [mrhan1993/Fooocus-API#21]
眼疾，可能要停更一段时间，非常抱歉

**Comment by 812913329** [comment]
Pay attention to rest. You can try German hyaluronic acid sodium hyaluronate eye drops for maintenance, if it can be used.

**Comment by pengpengzi** [comment]
Health is important, looking forward to the return.

**Comment by ImmNaruto** [comment]
大佬注意身体，早日康复
