### ISSUE TITLE
Inpaint is slow because of preparation time and model switching

### ISSUE THREAD

**Issue by CyrusVorwald** [mrhan1993/Fooocus-API#214]
Inpaint switches and loads models at initialization and again halfway through the steps. It takes about 4x as long as regular image generation between that and the preparation time. I tried setting `inpaint_disable_initial_latent` to true but it didn't impact timing very much.

**Comment by konieshadow** [comment]
To reduce cold start time, it only download base model files of the preset when startup. And when using adavance functions such as upscale, inpaint or outpaint, downloading on demand will happend. The interface provided by replicate cannot achieve very flexible use purposes.

**Comment by CyrusVorwald** [comment]
This occurs every time inpaint is run, even if done repeatedly within a short time period.

**Comment by konieshadow** [comment]
> This occurs every time inpaint is run, even if done repeatedly within a short time period.

I don't have much time to run much tests now. Can you compare it to local deployment (python main.py) and origin Fooocus?

**Comment by jareddr** [comment]
Sorry to ask a semi-unrelated question in this thread but how does one get inpainting to work?

What format should the image mask be?  I've tried both transparent + white pixels for my mask and transparent+black pixels for my mask.  Every time I try I just get a new image generation back taking up the whole canvas.

Here is how I have it set up on replicate
inpaint image
![image](https://github.com/konieshadow/Fooocus-API/assets/687347/2e75e906-66db-47e5-8a8a-9f9ba26a5df6)

inpaint mask (I've tried both black and white masks)
![image](https://github.com/konieshadow/Fooocus-API/assets/687347/c906450d-1d2a-41dc-af01-51daa171e171)

additional in paint prompt
![image](https://github.com/konieshadow/Fooocus-API/assets/687347/766aa6bd-2b7c-405d-a457-2236a2b9db04)


Then this is the output I get

![image](https://github.com/konieshadow/Fooocus-API/assets/687347/c979f03c-cf69-4f24-8340-b47e24e665e1)

**Comment by jareddr** [comment]
Sorry I answered my own question by looking at the code.  Mask is working great with black = no change and white = in paint.

![homer-simpson-bush-gif](https://github.com/konieshadow/Fooocus-API/assets/687347/342fd2cc-e10c-47fe-8615-1100e9b47380)
