### ISSUE TITLE
sys.argv

### ISSUE THREAD

**Issue by bytonylee** [mrhan1993/Fooocus-API#216]
In this code, default sys.argv is '/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cog/server/http.py'.
But to operate the code of Fooocus, it's not cog one.

I think that is why it doesn't work when we push it to replicate.
Is there any advice for this?

**Comment by konieshadow** [comment]
I haven't meet trouble when pushing code to replicate. However, I often encounter problems during the model startup phase of replicate. Can you share the codes and error messages?
