### ISSUE TITLE
 No module named 'modules.model_loader'

### ISSUE THREAD

**Issue by FSYFSYFSY** [mrhan1993/Fooocus-API#22]
I really appreciate your work, but I was encountering some wired envs problems, so I want to looking for some help here:

I see when we are running main.py, it will go clone the Fooocus, and there are sort of function depended on Fooocus. However, it does not directly work when I was following the instruction to run the project, it always error by cannot find the modules(or some .py file) as title in repositories/Fooocus.

If I move all things in fooocus out of dir, I will get error "No module named 'fcbh'", but it is seems not a package.

any idea?

**Comment by 812913329** [comment]
Check your own environment. I have tested several environments and have never encountered it.

**Comment by FSYFSYFSY** [comment]
> Check your own environment. I have tested several environments and have never encountered it.

Are you running it by docker? or just run main.py?

**Comment by FSYFSYFSY** [comment]
I found the reason;
I deploy the environment on my own rather than "create -f environment.yaml", so it causes a configuration error somewhere.
 I rebuilt the environment as instructed, the problem fixed
