### ISSUE TITLE
Foocus-api gets into an unrecoverable state after receving a prompt longer than 1024 tokens

### ISSUE THREAD

**Issue by bnogas** [mrhan1993/Fooocus-API#223]
Issue:
Whenever too long prompt is sent to fooocus-api it goes into an unrecoverable state. It fails all the subsequent requests after receving a single one with > 1024 tokens.  Additionally `/ping` endpoint still returns 200.

I'm attaching the server log:
[error.log](https://github.com/mrhan1993/Fooocus-API/files/14345218/error.log)

And an input that causes the issue
[input2.json](https://github.com/mrhan1993/Fooocus-API/files/14345173/input2.json)
```
curl -X POST -H "Content-Type: application/json" -d @input2.json http://foocus-api-address/v2/generation/image-prompt
```

**Comment by mrhan1993** [comment]
After my testing, it was confirmed that the problem exists. After using Focus for testing, I believe that this should be a support issue with Focus. As it cannot be resolved at the moment, it is recommended not to use it in this way.

**Comment by Demuzx** [comment]
I tested this on method v1/generation/text-to-image and this error also appears. We generate a lot of images per day and this error is very critical for us. For a long time we couldn’t understand what the problem was until we found this topic. We will have to cut the number of tokens. (((
