### ISSUE TITLE
Is there a way to specify the output filenames?

### ISSUE THREAD

**Issue by idris67** [mrhan1993/Fooocus-API#225]
Instead of having output files such as ``06a4437f-6ff7-4090-a50c-79d511127f94.png `` 
Could we specify the exact name we want to give to each image we generate? I'd like to run a script to generate thousands of prompts (text-to-image), so it would be easier for me to know which image corresponds to which prompt.
Thanks for the help!

**Comment by mrhan1993** [comment]
response include image name, you need not specify.
