### ISSUE TITLE
Support jpg and webp

### ISSUE THREAD

**Issue by appleplum** [mrhan1993/Fooocus-API#227]
It's already possible to change extension / image format in fooocus by changing the extension in private_logger.py
and then do something like this.
if image_extension == 'jpg' or image_extension == 'webp':
        Image.fromarray(img).save(local_temp_filename, quality=95, optimize=True, progressive=True)
    else:
        Image.fromarray(img).save(local_temp_filename)

**Comment by mrhan1993** [comment]
Planned

**Comment by PlexPt** [comment]
https://github.com/lllyasviel/Fooocus/pull/1863

**Comment by mrhan1993** [comment]
testing

**Comment by mrhan1993** [comment]
you can now update and have a try
