### ISSUE TITLE
How to reuse my existed env of Fooocus?

### ISSUE THREAD

**Issue by eric23** [mrhan1993/Fooocus-API#23]
I have installed Fooocus and MRE on my server. Is there any easy way to use the existing ones instead of downloading a new one?
I have no idea if the Fooocus in folder repository is duplicated.

**Comment by 812913329** [comment]
有，先把环境依赖安装好，你再把安装好了的Fooocus 文件夹移动到Fooocus api的repositories文件下代替就行，然后打开fooocus api即可，不用重新安装

**Comment by eric23** [comment]
> 有，先把环境依赖安装好，你再把安装好了的Fooocus 文件夹移动到Fooocus api的repositories文件下代替就行，然后打开fooocus api即可，不用重新安装

如果移动过来，fooocus和API可以同时运行吗？

另外我使用preset中用到的新模型，比如realisticStockPhoto_v10会报错，有遇到过吗？

**Comment by konieshadow** [comment]
也可以使用 user_path_config.txt 文件来配置模型的路径，格式和 Fooocus 的一样，理论上可以直接把 Fooocus 根目录下的 user_path_config.txt 复制过来，放到 Fooocus-API 根目录下。

两个项目可以同时运行的，只要内存和显存足够。

我没有试过第三方模型，理论上 Fooocus 支持的都支持。我晚点试下再回复。

**Comment by konieshadow** [comment]
我试了realisticStockPhoto_v10，还有 SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4 作为 lora，可以生成，效果还不错。

```
curl -X 'POST' \
  'http://127.0.0.1:8888/v1/generation/text-to-image?accept=image%2Fpng' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "prompt": "photograph close up portrait of Embraced couple enjoying in a movie in theatre , cinematic 4k epic detailed 4k epic detailed photograph shot on kodak detailed bokeh cinematic hbo dark moody",
  "negative_prompt": "",
  "style_selections": [
    "Fooocus V2",
    "Default (Slightly Cinematic)"
  ],
  "performance_selection": "Speed",
  "aspect_ratios_selection": "1152×896",
  "image_number": 1,
  "image_seed": -1,
  "sharpness": 2,
  "guidance_scale": 3,
  "base_model_name": "realisticStockPhoto_v10.safetensors",
  "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors",
  "loras": [
    {
      "model_name": "SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors",
      "weight": 0.5
    }
  ]
}'
```

**Comment by eric23** [comment]
> 我试了realisticStockPhoto_v10，还有 SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4 作为 lora，可以生成，效果还不错。

我用curl去单独调用是好的，但是在自己做的APP里调用API切换不同预设所使用的模型，比如sdxl切换到anime或者realistic所使用的模型就会报错。比如说：“896x1152”不在所接受的可选范围内。不知道是不是模型切换时是否需要做什么特殊处理...

**Comment by konieshadow** [comment]
> > 我试了realisticStockPhoto_v10，还有 SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4 作为 lora，可以生成，效果还不错。
> 
> 我用curl去单独调用是好的，但是在自己做的APP里调用API切换不同预设所使用的模型，比如sdxl切换到anime或者realistic所使用的模型就会报错。比如说：“896x1152”不在所接受的可选范围内。不知道是不是模型切换时是否需要做什么特殊处理...

如果报分辨率相关的问题，可能是由于模型不是 sdxl 版本的。

**Comment by eric23** [comment]
把报文中的分辨率改成896x1152就报错了，但是预设中写实类的默认分辨率就是896x1152。而这个分辨率其实在接受列表里
{
  "detail": [
    {
      "type": "enum",
      "loc": [
        "body",
        "aspect_ratios_selection"
      ],
      "msg": "Input should be '704×1408', '704×1344', '768×1344', '768×1280', '832×1216', '832×1152', '896×1152', '896×1088', '960×1088', '960×1024', '1024×1024', '1024×960', '1088×960', '1088×896', '1152×896', '1152×832', '1216×832', '1280×768', '1344×768', '1344×704', '1408×704', '1472×704', '1536×640', '1600×640', '1664×576' or '1728×576'",
      "input": "896x1152",
      "ctx": {
        "expected": "'704×1408', '704×1344', '768×1344', '768×1280', '832×1216', '832×1152', '896×1152', '896×1088', '960×1088', '960×1024', '1024×1024', '1024×960', '1088×960', '1088×896', '1152×896', '1152×832', '1216×832', '1280×768', '1344×768', '1344×704', '1408×704', '1472×704', '1536×640', '1600×640', '1664×576' or '1728×576'"
      }
    }
  ]
}

**Comment by eric23** [comment]
呃，问题找到了，我把报错的分辨率换成提示中的分辨率’896×1152‘就好了...
字符问题: ×x，第一个是api里的，第二个是小写的x，用第二个就报错，用第一个就可以。

models.py需要更新，模型名称和最新版对不上了。

**Comment by 812913329** [comment]
。。。真奇怪，为什么我一直收到邮件

**Comment by eric23** [comment]
> 。。。真奇怪，为什么我一直收到邮件

你在participants中，可以退出
