### ISSUE TITLE
How to set the name for saving the image?

### ISSUE THREAD

**Issue by YZBPXX** [mrhan1993/Fooocus-API#238]

**Comment by mrhan1993** [comment]
not support, More than one person has mentioned custom file names. Is there any scenario for this requirement? Why customize the file name?

**Comment by YZBPXX** [comment]
I have a batch of images that need to remove subtitles by inpainting, and I also hope to match the original image by naming the new image

**Comment by miraculix95** [comment]
customizing the file name is good when programmatically testing a prompt with a lot of different models and loras. Putting the lora and checkpoint name into the filename, helps identify the files

**Comment by mrhan1993** [comment]
#292
