### ISSUE TITLE
How can I use api key in requests

### ISSUE THREAD

**Issue by fredburtons** [mrhan1993/Fooocus-API#239]
Hi, cant  find any documentation about using of an api-key in requests

**Comment by mrhan1993** [comment]
`--apikey APIKEY` Set apikey to enable secure api
set request header `X-API-KEY` to your APIKEY

**Comment by thiner** [comment]
It's better update the ReadMe to include this header in a sample request. I am confused by this setting as well, have to search issues for answer.
