### ISSUE TITLE
Issues with Image Inpainting via POST /v1/generation/image-inpait-outpaint in Swagger Document

### ISSUE THREAD

**Issue by rockmanxyj** [mrhan1993/Fooocus-API#24]
I tried to reproduce the content in the examples using the POST /v1/generation/image-inpait-outpaint interface in the Swagger Document, but it was unsuccessful (as shown below):
![dog111](https://github.com/konieshadow/Fooocus-API/assets/3918235/738a569d-4535-4c0f-86c7-a52440dd1197)
![dogmask](https://github.com/konieshadow/Fooocus-API/assets/3918235/01c5c2ec-db8b-427f-85cf-3663c4ea23aa)
![2023-10-19_23-37-56_4622](https://github.com/konieshadow/Fooocus-API/assets/3918235/b30e114a-460a-43f7-b5de-6862e9dbec65)

 Here's the postdata:
```bash
curl -X 'POST' \
  'http://127.0.0.1:5592/v1/generation/image-inpait-outpaint?accept=image%2Fpng' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'sharpness=2' \
  -F 'input_mask=@dogmask.png;type=image/png' \
  -F 'guidance_scale=7' \
  -F 'prompt=an empty bench' \
  -F 'l1=' \
  -F 'input_image=@dog111.png;type=image/png' \
  -F 'l2=' \
  -F 'l3=' \
  -F 'l4=' \
  -F 'l5=' \
  -F 'image_number=1' \
  -F 'negative_prompt=' \
  -F 'base_model_name=sd_xl_base_1.0_0.9vae.safetensors' \
  -F 'image_seed=-1' \
  -F 'style_selections=Fooocus V2,Default (Slightly Cinematic)' \
  -F 'outpaint_selections=' \
  -F 'w1=' \
  -F 'w2=' \
  -F 'refiner_model_name=sd_xl_refiner_1.0_0.9vae.safetensors' \
  -F 'aspect_ratios_selection=' \
  -F 'w3=' \
  -F 'performance_selection=Quality' \
  -F 'w4=' \
  -F 'w5='

**Comment by konieshadow** [comment]
Confirmed that the problem does exist. I'll try to solve it by merging Fooocus' latest code first.

**Comment by konieshadow** [comment]
It seems like a issue with previous version of Fooocus. Already fixed by merging with latest Fooocus code. Please update code and try again.

**Comment by rockmanxyj** [comment]
thanks for your reply
