### ISSUE TITLE
How to generate images? (NOOB Question)

### ISSUE THREAD

**Issue by kilegence** [mrhan1993/Fooocus-API#240]
Hi, sorry for the noob question, it's probably an easy fix. I successfully opened the API at the URL: http://127.0.0.1:8888 and clicked on docs, and this opened up:
![image](https://github.com/mrhan1993/Fooocus-API/assets/158856809/6b884668-8c8a-498f-a82d-0907a7eda649)

Next I've opened up examples.ipynp and tried to write the prompt on the line where it says "image prompt" but when I run the command I get this error:
[Task Queue] Finish task with error, seq=bfb51913-cfa7-44a5-ae2c-e994b7ffc660

Did I do something wrong? How do I actually open Foocus with it to get it running and generate images? Can I do it locally on my PC or I need to use Replicate?

Thanks, btw I'm not a coder so this is so confusing to me haha

**Comment by mrhan1993** [comment]
Image Prompt using image to generate image. if you want to generate image by text, use /v1/generate/text-to-image endpoint
