### ISSUE TITLE
How can I get progress images during generation

### ISSUE THREAD

**Issue by alphaloop-vincent** [mrhan1993/Fooocus-API#242]
When using fooocus in the web client during generation it fetches the progress images each step. How can I do this using fooocus api?

**Comment by mrhan1993** [comment]
use async, and then use taskid query through `/v1/generation/query-job` [query-job](https://github.com/mrhan1993/Fooocus-API/blob/main/docs/api_doc_zh.md#%E6%9F%A5%E8%AF%A2%E4%BB%BB%E5%8A%A1--query-job)
