### ISSUE TITLE
[Task Queue] Already waiting for 20.0 seconds

### ISSUE THREAD

**Issue by pototao** [mrhan1993/Fooocus-API#244]
![image](https://github.com/mrhan1993/Fooocus-API/assets/1920490/e76848b4-f8f2-47f9-92de-6879aa9e7730)
大神，你好，请问这个是什么问题呢。一直也没报错，就是一直在队列等待。

**Comment by sumanthdonapati** [comment]
same issue, can someone help

**Comment by pototao** [comment]
> same issue, can someone help

I change to v0.3.29,it's done

**Comment by PeakLee** [comment]
same to  downgrade v0.3.29, then it works well
