### ISSUE TITLE
你好，我想问一下部署在colab中，怎么访问到？

### ISSUE THREAD

**Issue by LiangZhenDong** [mrhan1993/Fooocus-API#25]
使用Fooocus部署后有个一外网网址可以访问，但是这个api项目我在colab中部署完成后，ip也换成colab的ip了，访问[8888](http://127.0.0.1:8888/docs)访问不到

**Comment by konieshadow** [comment]
点击 Readme 中的 “Open in Colab” 按钮，运行笔记本后，会输出外网可访问的地址。原理是使用了隧道代理。
