### ISSUE TITLE
main.py file is crashing

### ISSUE THREAD

**Issue by piyushgit011** [mrhan1993/Fooocus-API#257]
while running main.py file it's crashing showing couldn't find presets.
any solution?

**Comment by piyushgit011** [comment]
![image](https://github.com/mrhan1993/Fooocus-API/assets/96625965/6c13f8c5-63e5-4d31-83c0-7947b9f74062)
here is the error

**Comment by mrhan1993** [comment]
copy presents in fooocus to fooocusapi root folder
