### ISSUE TITLE
It seems that it does not support version 2.3.0 of Lightning

### ISSUE THREAD

**Issue by DraGonPlan** [mrhan1993/Fooocus-API#258]
When I set performance_selection to Lightning, I receive an error message: 422 Unprocessable Entity
Is this a bug? Or is it true that the current version does not support Lightning for foocus2.3.0

**Comment by piyushgit011** [comment]
#257 hey @DraGonPlan ,
 can you help me with this , i am having trouble while setting it up

**Comment by mrhan1993** [comment]
i noticed  this function, but not support yet.My family has had some accidents, it may take half a month to complete the next update

**Comment by miraculix95** [comment]
all the best to your family

**Comment by evanchan1989** [comment]
all the best to your family

**Comment by mrhan1993** [comment]
#269 have a try

**Comment by chenav** [comment]
Hello, 

It does not work, cause when you POST a JSON asking for Lightning perf, the API answers:

```
{
    "detail": [
        {
            "type": "enum",
            "loc": [
                "body",
                "performance_selection"
            ],
            "msg": "Input should be 'Speed', 'Quality' or 'Extreme Speed'",
            "input": "Lightning",
            "ctx": {
                "expected": "'Speed', 'Quality' or 'Extreme Speed'"
            }
        }
    ]
}

```

Seems to be managed by predict.py

You can fix it by changing lines 32-33 of predict.py

```     

   performance_selection: str = Input( default='Lightning', 
                                          description="Performance selection", choices=['Speed', 'Quality', 'Extreme Speed', 'Lightning']),
```

Forked it, built it, deployed it: it works ;)

C.

**Comment by mrhan1993** [comment]
This file is used for replicate, I will update it later

**Comment by mrhan1993** [comment]
> Hello,
> 
> It does not work, cause when you POST a JSON asking for Lightning perf, the API answers:
> 
> ```
> {
>     "detail": [
>         {
>             "type": "enum",
>             "loc": [
>                 "body",
>                 "performance_selection"
>             ],
>             "msg": "Input should be 'Speed', 'Quality' or 'Extreme Speed'",
>             "input": "Lightning",
>             "ctx": {
>                 "expected": "'Speed', 'Quality' or 'Extreme Speed'"
>             }
>         }
>     ]
> }
> ```
> 
> Seems to be managed by predict.py
> 
> You can fix it by changing lines 32-33 of predict.py
> 
> ```
> 
>    performance_selection: str = Input( default='Lightning', 
>                                           description="Performance selection", choices=['Speed', 'Quality', 'Extreme Speed', 'Lightning']),
> ```
> 
> Forked it, built it, deployed it: it works ;)
> 
> C.

This file is used for replicate, I will update it later

**Comment by Glumby78** [comment]
I also get a 422 Unprocessable Entity error. I use the API in default. The API works great until it doesnt. It generates pictures from 10 to 80 minutes then I get the 422 error. I deinstalled everything and reinstalled it but the 422 error always comes back.

This is the last info from the console:
INFO:     127.0.0.1:62570 - "POST /v2/generation/image-prompt HTTP/1.1" 200 OK
INFO:     127.0.0.1:62574 - "GET /files/2024-11-04/3f59f5ae-4fdc-4802-a2d0-7464e692be15-0.png HTTP/1.1" 200 OK
[Fooocus Model Management] Moving model(s) has taken 0.54 seconds
Processing time (total): 106.81 seconds
INFO:     127.0.0.1:62580 - "POST /v2/generation/image-prompt HTTP/1.1" 422 Unprocessable Entity

**Comment by mrhan1993** [comment]
@LuckyPets can i have a look your code and request params

**Comment by Glumby78** [comment]
@mrhan1993 
[main.txt](https://github.com/user-attachments/files/17629482/main.txt)

I have just written to the developer of the tool I use. Currently, the function for the request params is not yet available in his tool. He wants to take care of it next week. Can you read anything from the console? I upload different versions that always end with the 422 error.
[Fooocus Python Konsole 2.txt](https://github.com/user-attachments/files/17629533/Fooocus.Python.Konsole.2.txt)
[Fooocus Python Konsole 3.txt](https://github.com/user-attachments/files/17629534/Fooocus.Python.Konsole.3.txt)
[Fooocus Python Konsole 4.txt](https://github.com/user-attachments/files/17629535/Fooocus.Python.Konsole.4.txt)
[Fooocus Python Konsole 5.txt](https://github.com/user-attachments/files/17629536/Fooocus.Python.Konsole.5.txt)
[Fooocus Python Konsole.txt](https://github.com/user-attachments/files/17629538/Fooocus.Python.Konsole.txt)

**Comment by mrhan1993** [comment]
422 means the format of your request data is invalid. I can do nothing before seeing the request data

**Comment by Glumby78** [comment]
All right. I'll get back to you as soon as I get the information.

**Comment by Glumby78** [comment]
This is what the developer of the tool sent to me.
[Parameters.txt](https://github.com/user-attachments/files/17748461/Parameters.txt)

Unfortunately the parameters and the prompt are not shown in the console when error 422 occurs. I only get this information if the action was successful.

**Comment by mrhan1993** [comment]
I just pushed a patch. Now the 422 problem can output the specific parameters received in the console. You can update it and try again.

by the way，I tried your parameters, I think the problem may be with several variable calculations, but I'm not quite sure yet. If possible, I hope you can update it and help troubleshoot this error.

**Comment by Glumby78** [comment]
Thank you! I will test it as soon as possible.
