### ISSUE TITLE
Faster start up environment?

### ISSUE THREAD

**Issue by Explotador72** [mrhan1993/Fooocus-API#27]
I've been using this project, and it's fantastic. I'm using it in Google Colab, and everything works well except for the initial startup. On a regular PC, it's a bit slow at the beginning, but it gets faster afterward.

However, in Google Colab, the initial startup takes 8 minutes, while the original Fooocus project only takes 2 minutes. Is there any way to optimize this? I don't have the technical expertise to do it myself. 
The main slowdown seems to be during downloads, especially during the initial execution of main.py.
And I have seen that the older version, like two weeks, was faster, initially take it only 3 minutes with now takes 8.

**Comment by davefojtik** [comment]
@Explotador72 I think this might be rather the chosen infrastructure and things that are not related to this project and that the author could somehow influence.

Google Colab has a few problems of its own.
- To make the storage persistent, people store their files on Google Drive and upload them to the workspace from there. This is of course quite slow.
- Even if you use local temporary storage, there is a CPU bottleneck. Also visible when uploading data to VRAM.

In order to achieve an increase in speed, you would have to try to optimize the infrastructure of the workspace, and in your case requirements installation itself.

For example in our [RunPod implementation](https://github.com/davefojtik/RunPod-Fooocus-API) - the container only turns on when an API request comes in and then turns off immediately, paying only for the execution time. But this also means that every API call is theoretically a cold-start. While in a frequent use, it is capable of outputting the image in ~7s, and with cold start in around 18s. So this API is not written slow :)

**Comment by MexNik** [comment]
> Я использую этот проект, и он фантастический. Я использую его в Google Colab, и все работает хорошо, за исключением первоначального запуска. Обычно ПК сначала он немного медленный, но потом становится быстрее.
> 
> Однако в Google Colab первоначальный запуск занимает 8 минут, исходный проект Fooocus — всего 2 минуты. Есть ли способ это улучшить? У меня нет технических знаний, чтобы сделать это самостоятельно. Основное замедление происходит во время загрузки, особенно во время первоначального выполнения main.py. И я видел, что старая версия, например, две недели, была быстрее: сначала это заняло всего 3 минуты, а теперь - 8.



> I've been using this project, and it's fantastic. I'm using it in Google Colab, and everything works well except for the initial startup. On a regular PC, it's a bit slow at the beginning, but it gets faster afterward.
> 
> However, in Google Colab, the initial startup takes 8 minutes, while the original Fooocus project only takes 2 minutes. Is there any way to optimize this? I don't have the technical expertise to do it myself. The main slowdown seems to be during downloads, especially during the initial execution of main.py. And I have seen that the older version, like two weeks, was faster, initially take it only 3 minutes with now takes 8.

How did you change the default address? "http://127.0.0.1:8888/"

**Comment by davefojtik** [comment]
@MexNik with flags `--port` and `--host`

_From readme:_

> For pragram arguments, see
> 
> python main.py -h

**Comment by Oyabi** [comment]
How did you run it in colabs? I'm trying to do same as you but the first cell does not finish so I can't run my script after that.
For your speed problem, maybe put Fooocus-API in google drive so it doesn't download model each time?

**Comment by konieshadow** [comment]
> How did you run it in colabs? I'm trying to do same as you but the first cell does not finish so I can't run my script after that. For your speed problem, maybe put Fooocus-API in google drive so it doesn't download model each time?

Running this project in colab is not an implementation goal. Unless colab supports larger memory by default and is more friendly for tunnels, there will be many problems anyway.

**Comment by Oyabi** [comment]
I found a way to use it in collaborations if anyone is interested.
```
%cd /content
!git clone https://github.com/konieshadow/Fooocus-API.git
%cd /content/Fooocus-API
!nohup python main.py --listen --preset realistic &
```
Then in another cell:
```python
import requests
import time

def is_webpage_available(url):
    try:
        response = requests.get(url)
        # Check if the status code is in the range of 2xx, indicating success
        return response.status_code // 100 == 2
    except requests.ConnectionError:
        return False


while not is_webpage_available(cfg.fooocus_host):
  print("waiting")
  time.sleep(1)
```

**Comment by Demuzx** [comment]
> I've been using this project, and it's fantastic. I'm using it in Google Colab, and everything works well except for the initial startup. On a regular PC, it's a bit slow at the beginning, but it gets faster afterward.
> 
> However, in Google Colab, the initial startup takes 8 minutes, while the original Fooocus project only takes 2 minutes. Is there any way to optimize this? I don't have the technical expertise to do it myself. The main slowdown seems to be during downloads, especially during the initial execution of main.py. And I have seen that the older version, like two weeks, was faster, initially take it only 3 minutes with now takes 8.

If you have the original pre-installed Foooсus with models, it will take a few seconds to launch. ~8-10 seconds.
