### ISSUE TITLE
生成的图像不对，元数据复制都生成的不一样

### ISSUE THREAD

**Issue by 812913329** [mrhan1993/Fooocus-API#272]
![yuan1](https://github.com/mrhan1993/Fooocus-API/assets/67380983/a327d0c4-1db7-4696-bbfd-6cb2787aff41)
![2024-04-06_23-46-52_4621](https://github.com/mrhan1993/Fooocus-API/assets/67380983/6b19f600-02ca-4c71-8b5d-6363fbd5b750)

动漫图像是用fooocus网页端生成的没问题，第一个是直接复制动漫图像的元数据生成的。很奇怪，之前同一个提示词网页和api生成的天差地别，不知道是咋回事。参数都基本统一了、
{
  "parameters": {
    "adm_guidance": "(1.5, 0.8, 0.3)",
    "base_model": "animaPencilXL_v100",
    "base_model_hash": "7ed8da12d9",
    "full_negative_prompt": [
      "(worst quality, low quality, normal quality, lowres, low details, oversaturated, undersaturated, overexposed, underexposed, bad photo, bad photography, bad art:1.4), (watermark, signature, text font, username, error, logo, words, letters, digits, autograph, trademark, name:1.2), (blur, blurry, grainy), morbid, ugly, asymmetrical, mutated malformed, mutilated, poorly lit, bad shadow, draft, cropped, out of frame, cut off, censored, jpeg artifacts, out of focus, glitch, duplicate, (bad hands, bad anatomy, bad body, bad face, bad teeth, bad arms, bad legs, deformities:1.3)"
    ],
    "full_prompt": [
      "solo, looking at viewer, short hair, bangs, brown hair, black hair, long sleeves, 1boy, brown eyes, closed mouth, male focus, expressionless, own hands together, backlighting, robe, male child, straight-on, white robe",
      "solo, looking at viewer, short hair, bangs, brown hair, black hair, long sleeves, 1boy, brown eyes, closed mouth, male focus, expressionless, own hands together, backlighting, robe, male child, straight-on, white robe, deep rich vivid colors, ambient atmosphere, sharp, extremely detailed, color, complex, beautiful"
    ],
    "guidance_scale": 7,
    "loras": [],
    "metadata_scheme": "fooocus",
    "negative_prompt": "",
    "performance": "Speed",
    "prompt": "solo, looking at viewer, short hair, bangs, brown hair, black hair, long sleeves, 1boy, brown eyes, closed mouth, male focus, expressionless, own hands together, backlighting, robe, male child, straight-on, white robe",
    "prompt_expansion": "solo, looking at viewer, short hair, bangs, brown hair, black hair, long sleeves, 1boy, brown eyes, closed mouth, male focus, expressionless, own hands together, backlighting, robe, male child, straight-on, white robe, deep rich vivid colors, ambient atmosphere, sharp, extremely detailed, color, complex, beautiful",
    "refiner_model": "sd_xl_refiner_1.0_0.9vae",
    "refiner_model_hash": "8d0ce6c016",
    "refiner_switch": 0.8,
    "resolution": "(896, 1152)",
    "sampler": "dpmpp_2m_sde_gpu",
    "scheduler": "karras",
    "seed": "8580493647943573046",
    "sharpness": 2,
    "steps": 30,
    "styles": "['Fooocus V2', 'Fooocus Semi Realistic']",
    "version": "Fooocus v2.3.1"
  },
  "metadata_scheme": "fooocus"
}

**Comment by 812913329** [comment]
并且指定的图像随机种子并不会生效，返回的种子和指定的不一样

**Comment by 812913329** [comment]
使用的fooocus版本2.31，不知道是否是这个的原因。但是我看已经支持到2.30了，应该也没啥区别

**Comment by mrhan1993** [comment]
模型名称要带上扩展名，否则使用默认模型，种子的话，传进去 int 类型，别加引号。
