### ISSUE TITLE
Issue with Running it locally

### ISSUE THREAD

**Issue by Mutai-Gilbert** [mrhan1993/Fooocus-API#277]
I'm having issues running the app locally on a Linux environment. I followed all the instructions, but I still can't seem to get it to work. I want to expose the different endpoints on paperspace.

**Comment by davefojtik** [comment]
Can you describe more what you mean by "to expose the api using docker compose" or what you're trying to do? It seems like you're trying to run the Fooocus-API in venv so what's the container for?

**Comment by Mutai-Gilbert** [comment]
I was able to run it locally successfully. However, I suggest improving your documentation as I found it challenging to run it locally using the Windows commands you provided. I will create an issue on this for future users.
