### ISSUE TITLE
image-prompt problem

### ISSUE THREAD

**Issue by LeapLu** [mrhan1993/Fooocus-API#28]
bg.jpeg:
![bg](https://github.com/konieshadow/Fooocus-API/assets/67357731/eafc4d0d-8ed3-47b7-b366-2b60ec59e59f)
robot.jpg:
![robot](https://github.com/konieshadow/Fooocus-API/assets/67357731/b8f08ab7-41c6-4b00-9b01-36a5d9a263e3)
command:
`curl -X 'POST'   '127.0.0.1:8888/v1/generation/image-prompt'   -H 'accept: application/json'   -H 'Content-Type: multipart/form-data'   -F 'sharpness=2'   -F 'cn_img1=@/data/api-scripts/robot.jpg;type=image/jpeg'   -F 'cn_img2=@/data/api-scripts/bg.jpeg;type=image/jpeg'   -F 'guidance_scale=7'   -F 'cn_type1=PyraCanny'   -F 'cn_img3='   -F 'prompt=bot'   -F 'cn_type2=Image Prompt'   -F 'cn_img4='   -F 'cn_weight1=2'   -F 'l1=sd_xl_offset_example-lora_1.0.safetensors'   -F 'cn_type3=Image Prompt'   -F 'cn_weight2=1'   -F 'l2='   -F 'cn_type4=Image Prompt'   -F 'cn_weight3=0'   -F 'l3='   -F 'cn_weight4=0'   -F 'l4='   -F 'l5='   -F 'image_number=1'   -F 'negative_prompt='   -F 'base_model_name=sd_xl_base_1.0_0.9vae.safetensors'   -F 'image_seed=-1'   -F 'style_selections=Fooocus V2,Default (Slightly Cinematic)'   -F 'w1=0.5'   -F 'w2=0.5'   -F 'refiner_model_name=sd_xl_refiner_1.0_0.9vae.safetensors'   -F 'cn_stop1=0.9'   -F 'aspect_ratios_selection=1152×896'   -F 'w3=0.5'   -F 'cn_stop2=0.5'   -F 'performance_selection=Speed'   -F 'w4=0.5'   -F 'cn_stop3=0'   -F 'w5=0.5'   -F 'cn_stop4=0'`
the dir:
```
(base) root@dell6:/data/api-scripts# ls
bg.jpeg  fooocus-img2img.py  fooocus-txt2img.py  robot.jpg
(base) root@dell6:/data/api-scripts# pwd
/data/api-scripts
(base) root@dell6:/data/api-scripts# 
```
however it return:
![image](https://github.com/konieshadow/Fooocus-API/assets/67357731/7aa7d9ed-1563-4a59-8be4-65b00a55a0f2)
I tried many times, it seems no relations to my cn_img1 and cn_img2, so I suspect that cn_img1 and cn_img2 two parameters maybe not working , anyone can help?

**Comment by LeapLu** [comment]
@konieshadow hello need your help please～

**Comment by konieshadow** [comment]
Maybe an issue with previous version of Fooocus. Just merged some code. Please update Fooocus-API' code and try again.

**Comment by LeapLu** [comment]
> Maybe an issue with previous version of Fooocus. Just merged some code. Please update Fooocus-API' code and try again.

thx It worked now~
