### ISSUE TITLE
haveing problems with modules 

### ISSUE THREAD

**Issue by spams12** [mrhan1993/Fooocus-API#284]
[{
	"resource": "/E:/Fooocus-API-main/main.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"modules.default_pipeline\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 69,
	"startColumn": 12,
	"endLineNumber": 69,
	"endColumn": 36
},{
	"resource": "/E:/Fooocus-API-main/main.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports",
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"modules\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 97,
	"startColumn": 10,
	"endLineNumber": 97,
	"endColumn": 17
}]

**Comment by mrhan1993** [comment]
Is this in IDE?

**Comment by spams12** [comment]
yeah i sovled it and added way to name the image file from the api
