### ISSUE TITLE
fooocus-api启动后，调用一次api之后就会一直占用显存？有办法清理吗？

### ISSUE THREAD

**Issue by DraGonPlan** [mrhan1993/Fooocus-API#287]
Fooocus-API后台运行后会一值占用GPU显存，大概11G左右，如何能API执行完成后，自动清理？而我单独使用Fooocus占用的显存只有5G左右。

还有我同时部署Fooocus-API以及InstantID，当运行InstantID的示例程序时，Fooocus-api的进程会被kill掉。

我使用的V100-32G显存的机器，应该不是显存不足造成的。

**Comment by mrhan1993** [comment]
你的占用怎么那么高，是哪个版本的？

![图片](https://github.com/mrhan1993/Fooocus-API/assets/50648276/7f3d483d-4945-4fe4-a779-eacb33252b75)

**Comment by DraGonPlan** [comment]
Fooocus以及Fooocus-api都是昨天新安装的，最新版本。先安装的Fooocus然后安装Fooocus-api，使用config.txt复用Fooocus的模型。

服务器是AutoDL的V100-32G，系统ubuntu20.04+CUDA11.8 使用的tmux+conda环境同时运行Fooocus以及Fooocus-api

Fooocus运行命令：python entry_with_update.py --port=6006

fooocus-api运行命令：python main.py --port=6009 --disable-image-log --webhook-url=http://127.0.0.1:8008/webhook

运行后，不调用api的情况下GPU状况：
![image](https://github.com/mrhan1993/Fooocus-API/assets/3086289/cb364013-e338-410d-befe-b2b04c7c1c36)
调用api文生图后GPU状况：
![image](https://github.com/mrhan1993/Fooocus-API/assets/3086289/fdc376c0-5a6e-4579-99ad-012667ef4c62)
之后闲置状态也一直是这样。
如果单独运行Fooocus，基本上是保持5G左右的显存占用。

**Comment by mrhan1993** [comment]
Fooocus和API同时运行吗。

明天我也租一台试试好了，你是哪个区租的？

**Comment by DraGonPlan** [comment]
北京C区，可用资源可能会有点紧张，我可以把我的服务器给你测试

**Comment by mrhan1993** [comment]
use `--always-low-vram --always-offload-from-vram` parameters

**Comment by DraGonPlan** [comment]
使用这个参数，关闭Fooocus，只启用Fooocus-API，显存占用4G左右，在可以接受的范围内了，多谢！
