### ISSUE TITLE
大哥，增加一个获取本地模型，还有并不会自动安装cuda

### ISSUE THREAD

**Issue by 812913329** [mrhan1993/Fooocus-API#29]
之前版本还会自动安装cuda，新版本后就不会自动安装了，要手动安装。

好像是只能手动安装2.0.1+cu188
默认是这个？https://download.pytorch.org/whl/cu121
121我尝试手动安装这个提示是没有这样的组合版本。

问题不大，还有希望有个更新日志，不然fooocusapi更新也不知道具体更新了什么。

**Comment by konieshadow** [comment]
只要本地的驱动版本和cuda版本不是太低，使用默认的配置自动安装依赖应该也是可以的。

每个版本的更新内容我会写在 release 页面，不过最近几个版本没啥好说的，主要是合并 Fooocus 的上游代码。
