### ISSUE TITLE
Replicate Generation failing

### ISSUE THREAD

**Issue by NaveenGTK** [mrhan1993/Fooocus-API#299]
Hello, thank you for the amazing work. Recently I pushed this model to Replicate with a custom checkpoint. But when I try to generate images I get the following error:

**Prediction failed.

ImageGenerationParams.__init__() missing 3 required positional arguments: 'save_meta', 'meta_scheme', and 'save_name'**

Error log:

`Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 259, in predict
params = ImageGenerationParams(
^^^^^^^^^^^^^^^^^^^^^^
TypeError: ImageGenerationParams.__init__() missing 3 required positional arguments: 'save_meta', 'meta_scheme', and 'save_name'`

**Comment by mrhan1993** [comment]
Do not use latest version, tag `v0.4.0.3` is the latest version have been tested and work well on replicate.
