### ISSUE TITLE
No module named ''fcbh"

### ISSUE THREAD

**Issue by gitmagox** [mrhan1993/Fooocus-API#30]
No module named ''fcbh"

**Comment by konieshadow** [comment]
Looks like Fooocus repository sync failed. Can you run `git branch` and `git log -n 5`, then reply with the outputs?

**Comment by gitmagox** [comment]
> Looks like Fooocus repository sync failed. Can you run `git branch` and `git log -n 5`, then reply with the outputs?

我的 Fooocus version = '2.1.728':https://github.com/lllyasviel/Fooocus/commit/4cf0c778da33fb91d591771bbe90123a45c54d3c
我暂时的解决方法,在main.py 中添加这几行代码可以跑起来.
`root = os.path.dirname(os.path.abspath(__file__))
backend_path = os.path.join(root, 'backend', 'headless')
if backend_path not in sys.path:
    sys.path.append(backend_path)`
