### ISSUE TITLE
What's the difference between endpoint v1 and v2 inpainting?

### ISSUE THREAD

**Issue by kexul** [mrhan1993/Fooocus-API#303]
Hi, I just noticed that there are two endpoint for inpainting, what's the difference? Thanks!
```
EndPoint_V1: /v1/generation/image-inpaint-outpaint
EndPoint_V2: /v2/generation/image-inpaint-outpaint
Method: Post
DataType: form|json
```

**Comment by kexul** [comment]
Do they use same algorithm under the hood but with different input parameters? 

![图片](https://github.com/mrhan1993/Fooocus-API/assets/5920217/240ef399-a558-49ce-97b5-ed6ee8b0e7f8)
![图片](https://github.com/mrhan1993/Fooocus-API/assets/5920217/e577a096-ac11-4f1c-b46b-c1d8524a0653)

**Comment by mrhan1993** [comment]
Except for the format of the request data, it is exactly the same

**Comment by kexul** [comment]
Thanks!
