### ISSUE TITLE
Access the gradio version?

### ISSUE THREAD

**Issue by kexul** [mrhan1993/Fooocus-API#304]
Hi, thanks for your great work!
Beside acess fooocus from API, sometimes I'd like to access it from gradio version, so I can modify some parameter and check the result in detail. Is it possible to access the fooocus gradio if only this repo is installed? Or maybe I need to install the original version of fooocus?

**Comment by mrhan1993** [comment]
From version 0.4.0.0, you need to install a stand alone Fooocus. Before that , you can starup Fooocus in repositories/Fooocus directory

**Comment by kexul** [comment]
Thanks!
