### ISSUE TITLE
请求openapi.json文档能更新

### ISSUE THREAD

**Issue by gitmagox** [mrhan1993/Fooocus-API#31]
Fooocus :2.1.60 以上的版本已经支持Realistic和Anime 
新模型可以跑起来
![image](https://github.com/konieshadow/Fooocus-API/assets/17232064/017d9ad7-8bc4-45d5-8216-6fbdfa543d84)

**Comment by konieshadow** [comment]
v0.2.1 版本刚刚更新过 openapi.json 文件，你可以试下。

**Comment by gitmagox** [comment]
谢谢收到
