### ISSUE TITLE
Default inpainting version

### ISSUE THREAD

**Issue by kexul** [mrhan1993/Fooocus-API#315]
Hi @mrhan1993 , the documentation here said default inpainting engine is V1:
![图片](https://github.com/mrhan1993/Fooocus-API/assets/5920217/a04d5071-82d3-438b-b8f7-02ba2e009a59)

But in my daily use of the original Fooocus GUI, the default inpainting engine is V2.6. 

Are we using V1 version if no advaced parameter is passed? Should we use V2.6 instead since it seems to be more advanced?

Thanks! 🤗

**Comment by mrhan1993** [comment]
default is 2.6, doc have a long time without update

**Comment by kexul** [comment]
Get it, thanks!
