### ISSUE TITLE
What this project does based on Fooocus ?

### ISSUE THREAD

**Issue by hqsh** [mrhan1993/Fooocus-API#317]
Is this project designed to make Fooocus an HTTP real-time waiting API? Or is it just to remove the Fooocus page and turn it into an external HTTP asynchronous task API, while the asynchronous task implementation remains the same as Fooocus?

Thank you!

**Comment by mrhan1993** [comment]
just to remove the Fooocus page and turn it into an external HTTP asynchronous task API,
