### ISSUE TITLE
[request]txt-to-image response Json add image url

### ISSUE THREAD

**Issue by qy8502** [mrhan1993/Fooocus-API#32]
If the generated image is stored disk, can you provide a url that can access the image multiple times.

**Comment by konieshadow** [comment]
I've thought about this.

This api is a thin layer apon Fooocus, and I thin it should be used as an internal service in real world project. You also need databases, load balance, distribute queue management, object storage service, ect to build a robust image generation service.

Additional considerations, the licesens of ComfyUI and Fooocus are GPL-3, so this api project must be GPL-3 too. But calling the api by http or rpc isn't limited by the licesens.

I want to add many features outside image generation itself. But it should be a new project, and maybe in later for my personal reason.

**Comment by konieshadow** [comment]
For your question. You can use async api for generations. Serve static files locally will make the api more complex.

**Comment by qy8502** [comment]
You've done a great job solving my big problem. I had to request gradio through websocket before your api. It was a terrible experience. If the connection is accidentally broken, the next drawing will be the wrong result of the last drawing.

But Fooocus gradio give me results contain a url such as http://192.168.100.81:7860/file=/tmp/gradio/dcdb7d5555df7e393dcc234d00d9d4f4430b6611/image.png.

Fooocus API also generates outputs/2023-10-25/log.html and outputs/2023-10-25/2023-10-25_10-26-09_6100.png files. Can you provide a url to get the output images such as http://192.168.100.81:8888/outputs/2023-10-25/2023-10-25_10-26-09_6100.png, and return the url in the response of txt-to-image.

**Comment by konieshadow** [comment]
@qy8502 Finished add file url for generation apis. Check the v0.3.0 release log: https://github.com/konieshadow/Fooocus-API/releases/tag/v0.3.0

**Comment by qy8502** [comment]
You are so great! Thank you!!
