### ISSUE TITLE
issue 327 中的问题 3，确认端口号没问题

### ISSUE THREAD

**Issue by hqsh** [mrhan1993/Fooocus-API#329]
https://github.com/mrhan1993/Fooocus-API/issues/327
能否麻烦看一下，刚刚在 issue 327 中回复您了，复制粘贴了容器内 python 命令行执行的输入输出，验证了端口号没问题。
因为在 issuc 327 中没有找到 reopen 按钮，所以又创建了这个 issue。

**Comment by mrhan1993** [comment]
你把timeout给成300再试试，手动下载 https://huggingface.co/lllyasviel/misc/resolve/main/model_base_caption_capfilt_large.pth 放到 repositories/Fooocus/models/ 下边再试试

**Comment by hqsh** [comment]
> 你把timeout给成300再试试，手动下载 https://huggingface.co/lllyasviel/misc/resolve/main/model_base_caption_capfilt_large.pth 放到 repositories/Fooocus/models/ 下边再试试

是模型文件没下载成功导致，需要翻墙。解决了谢谢
