### ISSUE TITLE
A blank page with `Swagger-UI to: /docs` on entering default url

### ISSUE THREAD

**Issue by Dj-Polyester** [mrhan1993/Fooocus-API#331]
When I enter http://127.0.0.1:8888. Just a webpage with  text [Swagger-UI to: /docs](http://127.0.0.1:8888/docs) pops up.

**Comment by mrhan1993** [comment]
click [/docs](http://127.0.0.1:8888/docs)

**Comment by Dj-Polyester** [comment]
So did you change the interface that was built with gradio?

**Comment by mrhan1993** [comment]
Yes, it provides a more customary way of programming
