### ISSUE TITLE
Support for AMD GPU

### ISSUE THREAD

**Issue by ryanrezrez** [mrhan1993/Fooocus-API#336]
I have an AMD GPU and I want to run Fooocus API with it, the problem is that it gives me this error: AssertionError: Torch not compiled with CUDA enabled. CUDA is for NVIDEA GPUs. Can you update it so that people that have AMD GPUs can install and use Fooocus API. The original Fooocus supports AMD GPUs.

**Comment by mrhan1993** [comment]
I can not test this, because i have no AMD GPU.
However, you can refer to [linux-amd-gpus](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-amd-gpus) to manually adjust the environment, and then use the `--skip-pip` parameter when launching Fooocus-API.
