### ISSUE TITLE
REST API documentation consistency improvements

### ISSUE THREAD

**Issue by alexvuka1** [mrhan1993/Fooocus-API#343]
I have identified the following possible instances of inconsistencies between this [Open API specification](https://github.com/mrhan1993/Fooocus-API/blob/4d4c8633b964abb1f1845d5ed98b0d53c7edfe10/docs/openapi.json) and its [Documentation](https://github.com/mrhan1993/Fooocus-API/blob/4d4c8633b964abb1f1845d5ed98b0d53c7edfe10/docs/api_doc_en.md):

- ### 🟩Found in Open API specification, 🟥Not found in Documentation
	- [ ] [`GET /`](https://github.com/mrhan1993/Fooocus-API/blob/4d4c8633b964abb1f1845d5ed98b0d53c7edfe10/docs/openapi.json)
	- [ ] [`GET /v1/generation/job-queue`](https://github.com/mrhan1993/Fooocus-API/blob/4d4c8633b964abb1f1845d5ed98b0d53c7edfe10/docs/openapi.json)
- ### 🟥Not found in Open API specification, 🟩Found in Documentation
	- [ ] [`POST /v1/engines/refresh-models`](https://github.com/mrhan1993/Fooocus-API/blob/4d4c8633b964abb1f1845d5ed98b0d53c7edfe10/docs/api_doc_en.md?plain=1#L668)
	- [ ] [`GET /v1/engines/job-queue`](https://github.com/mrhan1993/Fooocus-API/blob/4d4c8633b964abb1f1845d5ed98b0d53c7edfe10/docs/api_doc_en.md?plain=1#L739)

**About**

This is part of the evaluation of my Master's Project at Imperial College London. The section above is automatically generated and aims to expose API documentation inconsistencies in real-world GitHub repositories. The end goal is for the tool to be used as part of CI/CD, namely as a GitHub action. 

Hopefully, this is a step towards easier maintenance of API documentation. If you find this helpful, please consider updating the documentation to keep it in sync with the source code. I am also happy to assist with it, if appropriate. If this has not been useful, consider updating this issue with an explanation, so I can improve my approach. Thank you!

**Comment by mrhan1993** [comment]
[/v1/engines/refresh-models](https://github.com/mrhan1993/Fooocus-API/blob/4d4c8633b964abb1f1845d5ed98b0d53c7edfe10/docs/api_doc_en.md?plain=1#L668) has removed，may useful for older versions

**Comment by alexvuka1** [comment]
Thank you for the response and for pointing out the false positive.

The tool currently flags any discrepancies between the documented endpoints and the Open API specification to ensure consistency. However, I realise this can include depricated/removed endpoints, such as in your case.

Other than that, it flagged 3 more inconsistencies, are those valid?

Thank you again for your cooperation and understanding!
