### ISSUE TITLE
Pass command line arguments to Docker container

### ISSUE THREAD

**Issue by kickin6** [mrhan1993/Fooocus-API#366]
How do we pass command line arguments into the container?

**Comment by davefojtik** [comment]
You can overwrite the default CMD command and flags right in the docker run command:
```bash
docker run <image_name> <command> <flags>
```
___

Currently, the default Dockerfile CMD looks like this:
```Dockerfile
CMD ["python", "main.py", "--host", "0.0.0.0", "--port", "8888", "--skip-pip"]
```
Let's suppose you want to change the port. You can run the container with:
```bash
docker run <image_name> python main.py --host 0.0.0.0 --port 9999 --skip-pip
```

**Comment by kawikao** [comment]
That's what I ended up doing which works. Cheers.
