### ISSUE TITLE
The status code is 200, but returns a null value

### ISSUE THREAD

**Issue by WangQvQ** [mrhan1993/Fooocus-API#370]
Thanks for your work, I am having a problem in use, why the status code is 200 but returns a null value.
![image](https://github.com/mrhan1993/Fooocus-API/assets/58406737/f1471be1-b207-4a48-a3a8-25b84ee68796)
![image](https://github.com/mrhan1993/Fooocus-API/assets/58406737/6d73fb80-fd42-4b86-9e21-2cf9ebec0700)

**Comment by devsideal** [comment]
@WangQvQ were you able to resolve this issue?
