### ISSUE TITLE
Create model for Replicate

### ISSUE THREAD

**Issue by konieshadow** [mrhan1993/Fooocus-API#4]
You know, it's useful to implement a model supported by replicate.com, especially for those who don't have gpu machine locally.

**Comment by konieshadow** [comment]
Finished. The model is in [konieshadow/fooocus-api](https://replicate.com/konieshadow/fooocus-api).

**Comment by annamykol** [comment]
@konieshadow thanks for the deployment to replicate
I want to have my version of replicate there
Can you please tell me how much it costs? I just don't understand if the payment would be for the full-time my project would run. Or the payment would be just for the request to my project?
