### ISSUE TITLE
STEPS

### ISSUE THREAD

**Issue by M3chaKret** [mrhan1993/Fooocus-API#404]
Hi! I have a quick question about the settings. Sorry if this is obvious, but I can't seem to find the option for the number of steps in the generation process. Do any of the current settings correspond to that, and if not, how can I set it?

{
  "prompt": "",
  "negative_prompt": "",
  "style_selections": [
    "Fooocus V2",
    "Fooocus Enhance",
    "Fooocus Sharp"
  ],
  "performance_selection": "Speed",
  "aspect_ratios_selection": "1152*896",
  "image_number": 1,
  "image_seed": -1,
  "sharpness": 2,
  "guidance_scale": 4,
  "base_model_name": "juggernautXL_v8Rundiffusion.safetensors",
  "refiner_model_name": "None",
  "refiner_switch": 0.5,
  "loras": [
    {
      "enabled": true,
      "model_name": "sd_xl_offset_example-lora_1.0.safetensors",
      "weight": 0.1
    },
    {
      "enabled": true,
      "model_name": "None",
      "weight": 1
    },
    {
      "enabled": true,
      "model_name": "None",
      "weight": 1
    },
    {
      "enabled": true,
      "model_name": "None",
      "weight": 1
    },
    {
      "enabled": true,
      "model_name": "None",
      "weight": 1
    }
  ],
  "advanced_params": {
    "adaptive_cfg": 7,
    "adm_scaler_end": 0.3,
    "adm_scaler_negative": 0.8,
    "adm_scaler_positive": 1.5,
    "black_out_nsfw": false,
    "canny_high_threshold": 128,
    "canny_low_threshold": 64,
    "clip_skip": 2,
    "controlnet_softness": 0.25,
    "debugging_cn_preprocessor": false,
    "debugging_dino": false,
    "debugging_enhance_masks_checkbox": false,
    "debugging_inpaint_preprocessor": false,
    "dino_erode_or_dilate": 0,
    "disable_intermediate_results": false,
    "disable_preview": false,
    "disable_seed_increment": false,
    "freeu_b1": 1.01,
    "freeu_b2": 1.02,
    "freeu_enabled": false,
    "freeu_s1": 0.99,
    "freeu_s2": 0.95,
    "inpaint_advanced_masking_checkbox": true,
    "inpaint_disable_initial_latent": false,
    "inpaint_engine": "v2.6",
    "inpaint_erode_or_dilate": 0,
    "inpaint_respective_field": 1,
    "inpaint_strength": 1,
    "invert_mask_checkbox": false,
    "mixing_image_prompt_and_inpaint": false,
    "mixing_image_prompt_and_vary_upscale": false,
    "overwrite_height": -1,
    "overwrite_step": -1,
    "overwrite_switch": -1,
    "overwrite_upscale_strength": -1,
    "overwrite_vary_strength": -1,
    "overwrite_width": -1,
    "refiner_swap_method": "joint",
    "sampler_name": "dpmpp_2m_sde_gpu",
    "scheduler_name": "karras",
    "skipping_cn_preprocessor": false,
    "vae_name": "Default (model)"
  },
  "save_meta": true,
  "meta_scheme": "fooocus",
  "save_extension": "png",
  "save_name": "",
  "read_wildcards_in_order": false,
  "require_base64": false,
  "async_process": false,
  "webhook_url": ""
}

**Comment by mrhan1993** [comment]
overwrite_step
