### ISSUE TITLE
Missing argument 'refiner_switch'

### ISSUE THREAD

**Issue by thiner** [mrhan1993/Fooocus-API#47]
![image](https://github.com/konieshadow/Fooocus-API/assets/1897227/8a27037a-e7a0-48fb-a127-49b640eb25c5)

The argumet `refiner_switch_at` is important for different refiner models. But I couldn't find this argument in Fooocus-API request body. Please add this parameter.

**Comment by konieshadow** [comment]
Fixed in v0.3.10. Thanks for feedback.
