### ISSUE TITLE
Is it possible to return the image of the Running process in real time?

### ISSUE THREAD

**Issue by Kimdow220807** [mrhan1993/Fooocus-API#51]
Is it possible to return the image of the Running process in real time?

**Comment by ImmNaruto** [comment]
You can consider taking a look at the PNG image stream of the streaming output in api_utils.py/generation_output

**Comment by Kimdow220807** [comment]
> You can consider taking a look at the PNG image stream of the streaming output in api_utils.py/generation_output

Can you be more specific?

**Comment by ImmNaruto** [comment]
@Kimdow220807 You can enable the debug mode of your browser to see the streaming response of Fooocus on the web. It uses the image/png stream format. In the Fooocus API, this functionality is implemented in the function generation_output in api_utils.py. It checks for if streaming_output to determine whether to return the byte stream of the image.

**Comment by ImmNaruto** [comment]
@Kimdow220807 just like this.
![微信截图_20231113115253](https://github.com/konieshadow/Fooocus-API/assets/74526577/e0724e7b-6d6c-4cd7-ab3c-e7932cb8c535)

**Comment by Kimdow220807** [comment]
> @Kimdow220807 just like this. ![微信截图_20231113115253](https://user-images.githubusercontent.com/74526577/282359431-e0724e7b-6d6c-4cd7-ab3c-e7932cb8c535.png)

![B17FB6A9-1858-44cb-B98F-C2F98E474FFB](https://github.com/konieshadow/Fooocus-API/assets/57300391/7bfe19cb-314f-4163-9dd9-584c2d612930)
请问是这样吗？(query)这个参数去哪里找？

**Comment by ImmNaruto** [comment]
@Kimdow220807 accept里填写image/png，请求的那两个参数一个是在最后结果中返回base64，一个是异步获取job id，都和这个图片流没太大关系。你需要在页面前端指定这个接口链接，像这样：
![微信截图_20231114102355](https://github.com/konieshadow/Fooocus-API/assets/74526577/28beec08-c174-49ab-9082-38720f5a172f)

**Comment by konieshadow** [comment]
@Kimdow220807 It is posible. I may add it in `Query Job` api in next version.

**Comment by konieshadow** [comment]
Guys. Version v0.3.14 can use the [Query Job](https://github.com/konieshadow/Fooocus-API#query-job) api to obtain the preview image and execution progress at current time. If you want preview image, just pass true as `require_step_preivew` param.

It's not as same as the WebSocket stream style api. If anyone has a better idea, please share.

**Comment by Kimdow220807** [comment]
> @Kimdow220807 accept里填写image/png，请求的那两个参数一个是在最后结果中返回base64，一个是异步获取job id，都和这个图片流没太大关系。你需要在页面前端指定这个接口链接，像这样： ![微信截图_20231114102355](https://user-images.githubusercontent.com/74526577/282643865-28beec08-c174-49ab-9082-38720f5a172f.png)

謝謝

**Comment by Kimdow220807** [comment]
> Guys. Version v0.3.14 can use the [Query Job](https://github.com/konieshadow/Fooocus-API#query-job) api to obtain the preview image and execution progress at current current. If you want preview image, just pass true as `require_step_preivew` param.
> 
> It's not as same as the WebSocket stream style api. If anyone has a better idea, please share.

Thank you. Yes.
