### ISSUE TITLE
能把执行进度加入去吗？

### ISSUE THREAD

**Issue by yingshow** [mrhan1993/Fooocus-API#54]
现在API没有一个执行进度的反馈，需要查看执行进又要动原来的代码，是否方便把执行进度加入去，甚至可以把执行过程的图base64也可以查询出来就更好了

**Comment by konieshadow** [comment]
没办法通过一个普通的 Http 请求满足这样的需求，目前可以调用 ` /v1/generation/query-job` 接口获取生成进度，最好配合异步生成图片的方式（async_process 参数传 true）。

获取生成过程的预览图片的需求计划在下个小版本加上去。

**Comment by konieshadow** [comment]
@yingshow v0.3.14 版本可以使用 [Query Job](https://github.com/konieshadow/Fooocus-API#query-job) 接口获取当前生成过程中的预览图片和执行进度，`require_step_preivew` 参数传 true。

**Comment by yingshow** [comment]
@konieshadow  NB , 加油！

**Comment by zhangyuzhen1990** [comment]
> 现在API没有一个执行进度的反馈，需要查看执行进又要动原来的代码，是否方便把执行进度加入去，甚至可以把执行过程的图base64也可以查询出来就更好了

可以查询到过程图么

**Comment by zhangyuzhen1990** [comment]
> @yingshow v0.3.14 版本可以使用 [Query Job](https://github.com/konieshadow/Fooocus-API#query-job) 接口获取当前生成过程中的预览图片和执行进度，`require_step_preivew` 参数传 true。

可以查询到过程图么
