### ISSUE TITLE
还有一个问题，文件有重复存在

### ISSUE THREAD

**Issue by yingshow** [mrhan1993/Fooocus-API#56]
在Fooocus-API/outputs存在输出文件
在repositories/Fooocus/outputs 下也同样的文件，这个估计也要优化一下，应该只保留一份才是，不然太浪费空间了

**Comment by konieshadow** [comment]
是会有这个问题，有个参数可以禁用 Fooocus 自己的文件输出，运行 ```python main.py -h```，查看参数 `--disable-private-log` 的说明。
