### ISSUE TITLE
部分 PNG 图像在 Outpaint Direction 功能上结果不符合预期

### ISSUE THREAD

**Issue by mrhan1993** [mrhan1993/Fooocus-API#60]
这应该不是 Fooocus 自身问题，在 Fooocus 的 web 界面是没有问题的, 具体看下面的示例(除图片及方向选择, 其他全部使用默认参数, 方向为 Left, 具体参数在最后)：

![with_points](https://github.com/konieshadow/Fooocus-API/assets/50648276/ef51153e-48c6-46a6-b847-1160e53758b9)
![图片](https://github.com/konieshadow/Fooocus-API/assets/50648276/5fdc26d2-ff2a-4962-bd8f-56f848ac4699)

然后我把图片转换成 jpg，就可以正常使用
![with_points](https://github.com/konieshadow/Fooocus-API/assets/50648276/eeaab5b8-b7d2-4356-b5fe-4760f9b60226)
![图片](https://github.com/konieshadow/Fooocus-API/assets/50648276/95a6cad6-932a-4fe7-91b5-9519da82a0b6)

此外，在 #24 这个 Issues 里的那张 png 图片也会有这个问题, 同样的，转换成 jpg 之后正常
![s.png](https://user-images.githubusercontent.com/3918235/276679436-738a569d-4535-4c0f-86c7-a52440dd1197.png)
![图片](https://github.com/konieshadow/Fooocus-API/assets/50648276/472cb3f9-c3a2-48b7-837b-cd5cb5f612c3)

![图片](https://github.com/konieshadow/Fooocus-API/assets/50648276/9f0278ab-8594-4f17-b0a0-f3f013d16542)

```shell
curl -X 'POST' \
  'http://192.168.5.222:8888/v1/generation/image-inpait-outpaint' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'sharpness=2' \
  -F 'input_mask=' \
  -F 'loras=[{"model_name":"sd_xl_offset_example-lora_1.0.safetensors","weight":0.1}]' \
  -F 'advanced_params=' \
  -F 'guidance_scale=4' \
  -F 'prompt=' \
  -F 'input_image=@s.jpg;type=image/jpeg' \
  -F 'require_base64=false' \
  -F 'async_process=false' \
  -F 'image_number=1' \
  -F 'negative_prompt=' \
  -F 'refiner_switch=0.5' \
  -F 'base_model_name=juggernautXL_version6Rundiffusion.safetensors' \
  -F 'image_seed=-1' \
  -F 'style_selections=Fooocus V2,Fooocus Enhance,Fooocus Sharp' \
  -F 'inpaint_additional_prompt=' \
  -F 'outpaint_selections=Left' \
  -F 'refiner_model_name=None' \
  -F 'aspect_ratios_selection=1152×896' \
  -F 'performance_selection=Speed'
```

**Comment by konieshadow** [comment]
已在 v0.3.19 修复。多谢反馈。

**Comment by mrhan1993** [comment]
> 已在 v0.3.19 修复。多谢反馈。

老哥你是真勤奋啊

**Comment by mrhan1993** [comment]
> 已在 v0.3.19 修复。多谢反馈。

3.19没了？

**Comment by konieshadow** [comment]
> > 已在 v0.3.19 修复。多谢反馈。
> 
> 3.19没了？

Push到远程时失败了，因为网络问题...

**Comment by LeeKIngKIng** [comment]
我遇到的问题是只有base64格式才能扩图，url不行会重新随机生成
另外inpaint似乎也没作用，也是随机生成的图片

**Comment by mrhan1993** [comment]
我刚试了以下，我这里是可以的，你把URL给我一个我再试试。

**Comment by LeeKIngKIng** [comment]
我是本地开发的，暂无url，现在我是全部转换成base64处理。
inpaint我加了遮罩后生成的图变化很小，只是眼珠稍微变了，没有glasses的效果，我用的是v2，请问是需要什么特殊配置吗？
![image](https://github.com/mrhan1993/Fooocus-API/assets/16865056/dd8ba93c-92e3-4b21-ba45-57ffc360e3c5)
![origin](https://github.com/mrhan1993/Fooocus-API/assets/16865056/60ee0ebe-b5fa-489b-ac57-fd46fccf04ee)
![mask](https://github.com/mrhan1993/Fooocus-API/assets/16865056/62311e7c-c00b-43af-b9f8-1164497eaf78)

**Comment by mrhan1993** [comment]
你的Mask不太行。用下边的这个试试

![333071545-62311e7c-c00b-43af-b9f8-1164497eaf78](https://github.com/mrhan1993/Fooocus-API/assets/50648276/29389227-d0ab-4153-82e9-1ff4d46e921a)

![eeb8f32e-86be-4155-8cea-b3dcdf1af299-0](https://github.com/mrhan1993/Fooocus-API/assets/50648276/da710907-4a65-40ac-980d-86ba15ace295)
