### ISSUE TITLE
建议：新增图片分辨率自定义

### ISSUE THREAD

**Issue by xxddccaa** [mrhan1993/Fooocus-API#64]
用户传入的分辨率现在不是你这里面的备选项，你就会恢复默认。
但其实你可以指定到64的倍数的一个分辨率，然后生成图之后resize后返回给用户。

**Comment by konieshadow** [comment]
有一个方式是使用 config.txt 覆盖默认的分辨率配置。
完全自定义的输入应该也可以支持，等我完整测试过后试着加上去。

**Comment by xxddccaa** [comment]
其实这个默认的参数检查显得很呆。可以加的，我已经加了，就是不太优雅。。

**Comment by konieshadow** [comment]
在 v0.3.21 版本中，完全移除了对 `aspect_ratios_selection` 参数的输入限制。现在你可以输入任意合法的分辨率组合，比如 `1000*1000`。

**Comment by xxddccaa** [comment]
太到位了！
