### ISSUE TITLE
建议：不要存图

### ISSUE THREAD

**Issue by xxddccaa** [mrhan1993/Fooocus-API#65]
现在默认生成一张图就会在output文件夹里面进行存放，可以给可选参数让这个功能消息，只返回base64。

**Comment by xxddccaa** [comment]
不想要存图功能

**Comment by konieshadow** [comment]
最开始的版本是没有保存输出图片的，但是后面增加了异步请求和任务队列相关的接口，即使不需要以静态文件的方式返回图片，仍需要记录一份之前任务生成的图片内容，而保存在内存中又是不太合适的。

如果添加更多的参数来控制是否保存本地图片，会让接口变得过于臃肿。除非你有其他更好的建议？

**Comment by xxddccaa** [comment]
我是基于这个角度提出来的：
算法服务部署后，后端调用。专业的后端会去进行业务调度，我们算法服务不用抄心这个事情。所以是同步等待的就好。
不存图片的目的是为了算法部署后，不要让容器的存储一直会递增。

所以我认为即使过于臃肿，这个功能还是有用的，而且从一开始main.py就有配置项的话，整个代码更强大。当然，复杂的开发就是留给你自己的，我们用的人爽歪歪。

这个我用的时候已经改了，但不是优雅的。你如果有你的代码贡献进去，那就太好啦。

**Comment by konieshadow** [comment]
针对类似你的需求，在 v0.3.21 版本中，做了一些修补。如果已完成的任务数量超过了设定的队列历史上限，会同时清除内存中的任务信息和磁盘上保存的图片文件。

队列历史上限可以通过 --queue-history 参数在启动时设定。

**Comment by xxddccaa** [comment]
哥啊，猛！

**Comment by Laidawang** [comment]
![image](https://github.com/konieshadow/Fooocus-API/assets/85244566/5e4018c4-c89b-4824-823a-d306bb6c4a99)
似乎还会有一个这样的文件夹生成，这个可以也去掉吗？
