### ISSUE TITLE
inpaint outpatient method？

### ISSUE THREAD

**Issue by LeapLu** [mrhan1993/Fooocus-API#71]
<img width="787" alt="image" src="https://github.com/konieshadow/Fooocus-API/assets/67357731/99ea69d3-678a-43a4-a46b-97de9a3e7f1c">
hey! did inpaint outpatient method supported？I didnt find it from the api of /v2/generation/image-inpait-outpaint

**Comment by konieshadow** [comment]
Yes. You cound pass `outpaint_selections` for outpaint and `input_mask` for inpaint, both need param `input_image`.
The dropdown menu in your screenshot just fill some text in textfiled on the left, which equivalent to param `inpaint_additional_prompt` in the api.

**Comment by LeapLu** [comment]
so if there is the value of inpaint_additional_prompt which means the method is Modify Content?

**Comment by konieshadow** [comment]
Regardless of what the value of `inpaint_additional_prompt` is, it will apply inpaint if you pass param `input_mask`. 
The param `inpaint_additional_prompt` only influence the content of inpaint area. And from the Fooocus's code, the value of `inpaint_additional_prompt` will just override param `prompt`.

**Comment by LeapLu** [comment]
> Regardless of what the value of `inpaint_additional_prompt` is, it will apply inpaint if you pass param `input_mask`. The param `inpaint_additional_prompt` only influence the content of inpaint area. And from the Fooocus's code, the value of `inpaint_additional_prompt` will just override param `prompt`.

thank u! ❤️❤️❤️

**Comment by Laidawang** [comment]
@konieshadow 
![image](https://github.com/konieshadow/Fooocus-API/assets/85244566/e579cffc-8866-414a-8d59-be52b12e05a8)
As far as I know, there are three inpainting methods. What parameters do we use to control switching between them?

**Comment by Laidawang** [comment]
> @konieshadow ![image](https://private-user-images.githubusercontent.com/85244566/294418410-e579cffc-8866-414a-8d59-be52b12e05a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2Nzc5NzcsIm5iZiI6MTcwNDY3NzY3NywicGF0aCI6Ii84NTI0NDU2Ni8yOTQ0MTg0MTAtZTU3OWNmZmMtODg2Ni00MTRhLThkNTktYmU1MmIxMmUwNWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAxMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMTg1YWU1M2I4ZmIyYmNiZjlhY2RhMjFhMDgwYzg0Y2E1ZmMyOWNiZjUxZmE4NWUyZjc0NGQxNjhhZDEyYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P1gg3alIZTq7Vk4yDPzuqjLF0CAP9R7NW44mqttAPUk) As far as I know, there are three inpainting methods. What parameters do we use to control switching between them?

solved

**Comment by Shivanshmundra** [comment]
@Laidawang how did you switch between different ways? I am unable to find toggle.
