### ISSUE TITLE
Worker error: not enough values to unpack

### ISSUE THREAD

**Issue by yingshow** [mrhan1993/Fooocus-API#77]
Worker error: not enough values to unpack (expected 2, got 1)
[Task Queue] Finish task with error, seq=1

这是什么错误？

**Comment by yingshow** [comment]
[Fooocus Model Management] Moving model(s) has taken 0.31 seconds
[Task Queue] Task queue is free, start task, seq=1
[Parameters] Adaptive CFG = 7.0
[Parameters] Sharpness = 2.0
[Parameters] ADM Scale = 1.5 : 0.6 : 0.3
[Parameters] CFG = 1.0
Worker error: not enough values to unpack (expected 2, got 1)
[Task Queue] Finish task with error, seq=1

**Comment by yingshow** [comment]
原来是参数不完整

**Comment by ardha27** [comment]
i also got this error, how did you fix it?
