### ISSUE TITLE
Git clone failed for Fooocus: failed to connect to github.com: Connection timed out

### ISSUE THREAD

**Issue by rayadaschn** [mrhan1993/Fooocus-API#79]
Sorry 🙏 ，I found that this problem seems to exist in [Issue 41](https://github.com/konieshadow/Fooocus-API/issues/41) ，but this problem seems to have reappeared in [v0.3.22](https://github.com/konieshadow/Fooocus-API/releases/tag/v0.3.22):

When I run `python main.py`，（o´ﾟ□ﾟ`o）：

```bash
[Fooocus-API] Task queue size: 3, queue history size: 100
Traceback (most recent call last):
  File "/home/Fooocus-API/main.py", line 378, in <module>
    if prepare_environments(args):
  File "/home/Fooocus-API/main.py", line 286, in prepare_environments
    import modules.config as config
ModuleNotFoundError: No module named 'modules'
```

👀 It seems that the server container can not access github, so how to use it in China? (PS. The server can connect to github.com (140.82.114.4))

(ÒܫÓױ) Therefore, when I use docker to start the service, I also have such a problem. 

```bash
 Task queue size: 3, queue history size: 100
 
 Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors" to /app/repositories/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors
```

**Comment by mrhan1993** [comment]
你这纯粹网络问题，你要是可以正常克隆项目，可以手动克隆 https://github.com/lllyasviel/Fooocus 到 Fooocus-API/repositories 目录下，模型也是，你可以手动放到 Fooocus 下的 models 中，如果你实在是找不到， https://www.alipan.com/s/sz29tt8VJPf ，用这个 models 目录，基本包含所有默认使用的模型

**Comment by mrhan1993** [comment]
你这纯粹网络问题，你要是可以正常克隆项目，可以手动克隆 https://github.com/lllyasviel/Fooocus 到 Fooocus-API/repositories 目录下，模型也是，你可以手动放到 Fooocus 下的 models 中，https://www.123pan.com/s/dF5A-wzAsh.html 提取码: KiRg

**Comment by rayadaschn** [comment]
> 你这纯粹网络问题，你要是可以正常克隆项目，可以手动克隆 https://github.com/lllyasviel/Fooocus 到 Fooocus-API/repositories 目录下，模型也是，你可以手动放到 Fooocus 下的 models 中，https://www.123pan.com/s/dF5A-wzAsh.html 提取码: KiRg

٩(๑>◡<๑)۶ 好人一生平安！！！
