### ISSUE TITLE
How you made it?

### ISSUE THREAD

**Issue by Explotador72** [mrhan1993/Fooocus-API#8]
I'm trying to make a bot using fooocus, and I saw your repository. First of all, unfortunately I can't use it because local port don't work, I don't know why.
And secondly, how you past the parameters like promps, image style.... It the thing I can't solve.

Thanks

**Comment by konieshadow** [comment]
I looked at Fooocus's code, even not very in-depth. But I found that the entrypoint is in the file async_worker.py. So my main job became to rewrite the file, remove all Gradio-related code, and instead obtain the required parameters from the FastAPI request body.

There's no magic, it's just Python calling Python code.

You can just run my Fooocus-API project with docker, it can generate same picture by same pamameters as Fooocus. Fell free to ask me if you get deployment problems.

The api doc is in [openapi.json](https://raw.githubusercontent.com/konieshadow/Fooocus-API/main/docs/openapi.json) file, you can import it in swagger-ui editor.

**Comment by Explotador72** [comment]
Thanks, I was able to execute and try it. It worked, and I understood the most of the code.

But one thing, how I can make to create a public url to pass the json from one device to the pc?

**Comment by konieshadow** [comment]
If you are debugging locally, you need to keep your device and PC in the same LAN, and then the device can access the API through the PC's LAN IP and service port. In a production environment, your PC (more likely a server) needs to have a public IP.

Either way, this is beyond the scope of Fooocus.

**Comment by Explotador72** [comment]
Ok, I can execute the program perfectly in my pc and make a public url:
But when I try in a google colab, only to execute, it says: On field "loras" the following field constraints are set but not enforced: max_length. 
All the currencies are installed by requirements.txt so I don't understand what happen.

**Comment by Explotador72** [comment]
Ok, solve it. I only deleted the max_lenght from models.py in line 270. Thanks

**Comment by Explotador72** [comment]
Thanks for all, I finally complet my objective and I could create a discord image creator.
PD: With ngrok you can make your http public.
