### ISSUE TITLE
Worker error: User specified autocast device_type must be 'cuda' or 'cpu'

### ISSUE THREAD

**Issue by rayadaschn** [mrhan1993/Fooocus-API#80]
Oops!  (ಥ_ಥ) When I start fooocus to draw, the terminal reports an error: "`Worker error: User specified autocast device_type must be 'cuda' or 'cpu'.`"

Therefore, I think fooocus did not set the device number of cuda properly. However, when the program starts, there is output that the device configuration is correct:
"`Device: cuda:0 NVIDIA A40 : native`"

Finally, I set the cuda device id:  I fixed the cuda device in `main.py` and the problem was solved. 

```python
"os.environ['CUDA_VISIBLE_DEVICES'] = xxx "
```

Is there an easier way? T^T

**Comment by konieshadow** [comment]
You can also set `CUDA_VISIBLE_DEVICES` in environment variable.

**Comment by rayadaschn** [comment]
> You can also set `CUDA_VISIBLE_DEVICES` in environment variable.

Thx. (๑•̀ㅂ•́)و✧
