### ISSUE TITLE
Can we specify LoRAs or base models on Replicate.com?

### ISSUE THREAD

**Issue by rossheat** [mrhan1993/Fooocus-API#85]
Thank you for creating this excellent project. 

Can we specify our own LoRAs, or custom base models, when using this package via Replicate.com? 

I could not see any examples of this in the project's README or examples section. 

If this is currently not supported, do you plan on supporting it in the future?

**Comment by konieshadow** [comment]
Specify LoRAs or base models require downloading model files at the generation task submit steps, it will make the request very slow. And you need to config the download urls for each model.
It's like sort of disadvantages of serverless platform as Replicate.com.

But if you have a good idea, welcome to discuss it.
