### ISSUE TITLE
"Vary (strong)" does not work on the Replicate website

### ISSUE THREAD

**Issue by nickonai** [mrhan1993/Fooocus-API#86]
Thank you for your work!
Please check: Fooocus Vary (strong) does not work on the Replicate website.
But Vary (subtle) works well.

I tried: konieshadow/fooocus-api and konieshadow/fooocus-api-realistic

**Comment by konieshadow** [comment]
@intrening I just tested `Vary (Strong)` on the demo page of konieshadow/fooocus-api, and it works fine. Are you using the API? Can you share the request parameters?

**Comment by nickonai** [comment]
Sorry, it works fine!
