### ISSUE TITLE
Please update the version that supports Fooocus

### ISSUE THREAD

**Issue by Tomorrowxxy** [mrhan1993/Fooocus-API#88]
Current version：https://github.com/lllyasviel/Fooocus/blob/main/fooocus_version.py

**Comment by konieshadow** [comment]
@Tomorrowxxy Just merged latest Fooocus version. You can try it and feedback.

**Comment by mrhan1993** [comment]
> @Tomorrowxxy Just merged latest Fooocus version. You can try it and feedback.

虽然你刚刚更新，但版本号已经是 839 了 ==

**Comment by hannesfant** [comment]
Thanks for updating it. Just gave it a try, however it looks like the parameters aren't optional anymore: "ImageGenerationParams.__init__() missing 6 required positional arguments: 'upscale_value', 'outpaint_distance_left', 'outpaint_distance_right', 'outpaint_distance_top', 'outpaint_distance_bottom', and 'inpaint_additional_prompt'"

**Comment by miraculix95** [comment]
Hi there, I have installed Fooocus and it is great, but I am missing the API functionality. I have tried out the API documentation that pops up in the browser UI in the footer, but it did not work for me.

Now I would like to use Fooocus-API, with external services like replicate or using docker. 
I have installed my Fooocus directly without using conda or venv.

To be honest I have no idea what I need to do. Just copy all the files in the foocus folder, rerun the environment?
Can you explain it for a 5 year old?
