### ISSUE TITLE
问题：如何减少模型文件加载时间

### ISSUE THREAD

**Issue by xxddccaa** [mrhan1993/Fooocus-API#91]
fooocus作者回答使用--disable-offload-from-vram，我不知道如何应用到这个API项目中，大佬有建议吗？

**Comment by konieshadow** [comment]
@xddun Fooocus 目前加了很多命令行参数，我计划在下个版本添加对这些命令行参数的兼容支持。

**Comment by xxddccaa** [comment]
这是一个很大的工作量，加油！

**Comment by konieshadow** [comment]
@xddun 刚在 dev 分支添加了对 Fooocus 命令行参数的初步支持，如果可以的话，请帮忙测试并反馈问题。多谢！
