### ISSUE TITLE
Task Queue Not Working Properly When There Are Multiple Instances

### ISSUE THREAD

**Issue by thiner** [mrhan1993/Fooocus-API#92]
I deployed Fooocus-API to k8s cluster, and started two pods to serve client request. When client enable async request, the query job status request may fail and get a 404 response. This is caused by the job queue design. The job queue is not centralized, so the job id is not unique among all instances.

![Untitled Diagram-Page-8 drawio](https://github.com/konieshadow/Fooocus-API/assets/1897227/6362396d-8028-409e-9b3a-60b9a48f0ebd)

**Comment by mrhan1993** [comment]
Fooocus api is not currently designed for clusters, so what you say happens when you schedule to another Pod, you can try using service's LeastConnection load balancing method, or Session Affinity to ensure that requests are always routed to the correct Pod
