### ISSUE TITLE
The api cannot be used.

### ISSUE THREAD

**Issue by hailowck** [mrhan1993/Fooocus-API#96]
Help, why can't my api be used, even if it has been added to the environment variable?Is it because api charges?

**Comment by mrhan1993** [comment]
@hailowck more detail

**Comment by hailowck** [comment]
@mrhan1993 
<img width="891" alt="屏幕截图 2023-12-16 192729" src="https://github.com/konieshadow/Fooocus-API/assets/149397024/7a71fdef-e420-4178-8518-5b29dd5d5fec">
<img width="728" alt="屏幕截图 2023-12-16 192333" src="https://github.com/konieshadow/Fooocus-API/assets/149397024/1363ac99-2301-4a2e-8144-510758b76af2">
<img width="955" alt="屏幕截图 2023-12-16 192325" src="https://github.com/konieshadow/Fooocus-API/assets/149397024/ba91bdd5-a31c-4e89-8d01-8a5b9ed7c80b">

**Comment by hailowck** [comment]
@mrhan1993 This questions

**Comment by hailowck** [comment]
@mrhan1993 
this
<img width="1151" alt="屏幕截图 2023-12-18 144450" src="https://github.com/konieshadow/Fooocus-API/assets/149397024/9a4c6dee-f506-4acb-84bf-3f65b4458abf">

**Comment by mrhan1993** [comment]
```python
import replicate
import os
os.environ['REPLICATE_API_TOKEN'] = 'USE_YOUR_TOKEN_REPLACE'
output = replicate.run(
  "konieshadow/fooocus-api-anime:3b1d4e280c9427ad6616b47a08e17ea03f25c4851bdb039dc86fd552fc49fff4",
  input={
    "prompt": "1 girl",
    "cn_type1": "ImagePrompt",
    "cn_type2": "ImagePrompt",
    "cn_type3": "ImagePrompt",
    "cn_type4": "ImagePrompt",
    "sharpness": 2,
    "image_seed": 6752341482620184000,
    "uov_method": "Disabled",
    "image_number": 1,
    "guidance_scale": 7,
    "refiner_switch": 0.66,
    "negative_prompt": "(embedding:unaestheticXLv31:0.8), low quality, watermark",
    "style_selections": "Fooocus V2,Fooocus Masterpiece,SAI Anime,SAI Digital Art,SAI Enhance,SAI Fantasy Art",
    "outpaint_selections": "",
    "performance_selection": "Speed",
    "aspect_ratios_selection": "1152×896"
  }
)
print(output)
```


![图片](https://github.com/konieshadow/Fooocus-API/assets/50648276/394e0bd0-2774-4beb-9fc9-888cee95fd18)

**Comment by hailowck** [comment]
> ```python
> 进口 复制
> 进口 操作系统
> 操作系统.环境['复制API_TOKEN'] = 'USE_YOUR_TOKEN_REPLACE'
> 输出 = 复制.运行(
>   "konieshadow/fooocus-api-anime:3b1d4e280c9427ad6616b47a08e17ea03f25c4851bdb039dc86fd552fc49fff4",
>   输入={
>     “提示”: “1个女孩”,
>     "cn_type1": "图像提示",
>     "cn_type2": "图像提示",
>     "cn_type3": "图像提示",
>     "cn_type4": "图像提示",
>     “锐度”: 2,
>     "图像种子": 6752341482620184000,
>     "uov_method": "已禁用",
>     "图像编号": 1,
>     "指导_比例": 7,
>     "优化器开关": 0.66,
>     "negative_prompt": （嵌入：不美学XLv31:0.8 ） ，质量低，水印”,
>     "样式选择": “Foocus V2、Foocus杰作、SAI动漫、SAI数字艺术、SAI增强、SAI奇幻艺术”,
>     "外漆选择": "",
>     "性能选择": “速度”,
>     "宽高比选择": "1152×896"
>   }
> )
> 印刷品(输出)
> ```
> 
> ![图片](https://private-user-images.githubusercontent.com/50648276/291183240-394e0bd0-2774-4beb-9fc9-888cee95fd18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTM2NTMsIm5iZiI6MTcwMjk1MzM1MywicGF0aCI6Ii81MDY0ODI3Ni8yOTExODMyNDAtMzk0ZTBiZDAtMjc3NC00YmViLTlmYzktODg4Y2VlOTVmZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDAyMzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZmZkNDA0ZmM2ODkyZGI4YWM2N2YzNjIzOTNlZjM1NjUyMjZhZWM0MWEyYzNlMDY2NGUyNTZjNjg3NDA1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SRRpTTxKEtG8UT7pWjwNUtRyUgL5Py849057jhlyLFk)

Ok, thank you very much.
